/**
 * Production-ready Banglish → Bangla transliteration engine.
 *
 * Architecture:
 *  1. WORD_DICT — hand-curated dictionary (300+ entries) covering loanwords,
 *     brand names, e-commerce terms, and common Bangla vocabulary whose Avro
 *     phonetic output is wrong or unnatural.
 *  2. Smart variations — plural / suffix stripping, common misspellings.
 *  3. Avro phonetic fallback — for every word not found in the dictionary.
 *
 * Public API:
 *  transliterateWord(word)  → best Bangla form for one word
 *  transliterateText(text)  → converts a full phrase word-by-word
 *  getSuggestions(partial)  → prefix-search the dict for autocomplete
 *  convertBanglishToBangla  → alias for transliterateText
 *  transliterate            → alias for transliterateText
 */

import { toBangla as avroParse } from './avroPhoneticEngine';

// ─── Dictionary ───────────────────────────────────────────────────────────────
// Keys are lowercase, no spaces.  Values are proper Bengali Unicode.
const WORD_DICT: Record<string, string> = {
  // ── Technology & Electronics ─────────────────────────────────────────────
  mobile:         'মোবাইল',
  mobil:          'মোবাইল',
  mobaile:        'মোবাইল',
  smartphone:     'স্মার্টফোন',
  smartfon:       'স্মার্টফোন',
  phone:          'ফোন',
  fon:            'ফোন',
  computer:       'কম্পিউটার',
  komputer:       'কম্পিউটার',
  kompiutar:      'কম্পিউটার',
  computar:       'কম্পিউটার',
  pc:             'পিসি',
  laptop:         'ল্যাপটপ',
  laeptop:        'ল্যাপটপ',
  laptob:         'ল্যাপটপ',
  notebook:       'নোটবুক',
  notbuk:         'নোটবুক',
  tablet:         'ট্যাবলেট',
  taeblet:        'ট্যাবলেট',
  tab:            'ট্যাব',
  internet:       'ইন্টারনেট',
  intarnet:       'ইন্টারনেট',
  net:            'নেট',
  wifi:           'ওয়াইফাই',
  waifai:         'ওয়াইফাই',
  bluetooth:      'ব্লুটুথ',
  blututh:        'ব্লুটুথ',
  blutus:         'ব্লুটুথ',
  television:     'টেলিভিশন',
  tv:             'টিভি',
  tivi:           'টিভি',
  smarttv:        'স্মার্ট টিভি',
  ledtv:          'এলইডি টিভি',
  camera:         'ক্যামেরা',
  kaemara:        'ক্যামেরা',
  camara:         'ক্যামেরা',
  webcam:         'ওয়েবক্যাম',
  keyboard:       'কীবোর্ড',
  kibord:         'কীবোর্ড',
  mouse:          'মাউস',
  maus:           'মাউস',
  monitor:        'মনিটর',
  monitar:        'মনিটর',
  speaker:        'স্পিকার',
  speekar:        'স্পিকার',
  headphone:      'হেডফোন',
  headfon:        'হেডফোন',
  earphone:       'ইয়ারফোন',
  earfon:         'ইয়ারফোন',
  earbuds:        'ইয়ারবাড',
  microphone:     'মাইক্রোফোন',
  mike:           'মাইক',
  charger:        'চার্জার',
  charjar:        'চার্জার',
  battery:        'ব্যাটারি',
  baetari:        'ব্যাটারি',
  powerbank:      'পাওয়ারব্যাংক',
  cable:          'ক্যাবল',
  kebal:          'ক্যাবল',
  adapter:        'অ্যাডাপ্টার',
  printer:        'প্রিন্টার',
  printar:        'প্রিন্টার',
  scanner:        'স্ক্যানার',
  skaenaar:       'স্ক্যানার',
  router:         'রাউটার',
  rautar:         'রাউটার',
  projector:      'প্রজেক্টর',
  smartwatch:     'স্মার্টওয়াচ',
  electronics:    'ইলেকট্রনিক্স',
  ilektronics:    'ইলেকট্রনিক্স',
  electrical:     'ইলেকট্রিকাল',
  software:       'সফটওয়্যার',
  hardware:       'হার্ডওয়্যার',
  gaming:         'গেমিং',
  game:           'গেম',
  accessories:    'আনুষাঙ্গিক',
  gadget:         'গ্যাজেট',
  gadgets:        'গ্যাজেটস',

  // ── Refrigerator & Home Appliances ──────────────────────────────────────
  refrigerator:   'রেফ্রিজারেটর',
  fridge:         'ফ্রিজ',
  frij:           'ফ্রিজ',
  ac:             'এয়ার কন্ডিশনার',
  airconditioner: 'এয়ার কন্ডিশনার',
  fan:            'ফ্যান',
  ceilingfan:     'সিলিং ফ্যান',
  washingmachine: 'ওয়াশিং মেশিন',
  oven:           'ওভেন',
  microwave:      'মাইক্রোওয়েভ',
  blender:        'ব্লেন্ডার',
  mixer:          'মিক্সার',
  iron:           'আয়রন',
  vacuum:         'ভ্যাকুয়াম',
  generator:      'জেনারেটর',
  ups:            'ইউপিএস',
  inverter:       'ইনভার্টার',
  switchboard:    'সুইচবোর্ড',
  socket:         'সকেট',

  // ── Brands ───────────────────────────────────────────────────────────────
  samsung:        'স্যামসাং',
  saemsung:       'স্যামসাং',
  apple:          'অ্যাপল',
  aepel:          'অ্যাপল',
  iphone:         'আইফোন',
  ipad:           'আইপ্যাড',
  macbook:        'ম্যাকবুক',
  nokia:          'নকিয়া',
  sony:           'সনি',
  lg:             'এলজি',
  realme:         'রিয়েলমি',
  rialme:         'রিয়েলমি',
  xiaomi:         'শাওমি',
  shaomi:         'শাওমি',
  oppo:           'অপো',
  vivo:           'ভিভো',
  oneplus:        'ওয়ানপ্লাস',
  google:         'গুগল',
  facebook:       'ফেসবুক',
  amazon:         'আমাজন',
  emajon:         'আমাজন',
  microsoft:      'মাইক্রোসফট',
  lenovo:         'লেনোভো',
  asus:           'আসুস',
  hp:             'এইচপি',
  dell:           'ডেল',
  acer:           'এসার',
  huawei:         'হুয়াওয়ে',
  motorola:       'মটোরোলা',
  techno:         'টেকনো',
  infinix:        'ইনফিনিক্স',
  walton:         'ওয়ালটন',
  symphony:       'সিম্ফনি',
  singer:         'সিঙ্গার',
  minister:       'মিনিস্টার',
  vision:         'ভিশন',
  rangs:          'রঙস',

  // ── E-commerce & Shopping ────────────────────────────────────────────────
  ecommerce:      'ই-কমার্স',
  'e-commerce':   'ই-কমার্স',
  'e commerce':   'ই-কমার্স',
  shopping:       'শপিং',
  shoping:        'শপিং',
  shop:           'শপ',
  order:          'অর্ডার',
  ordar:          'অর্ডার',
  delivery:       'ডেলিভারি',
  delivari:       'ডেলিভারি',
  payment:        'পেমেন্ট',
  peiment:        'পেমেন্ট',
  discount:       'ডিসকাউন্ট',
  diskount:       'ডিসকাউন্ট',
  offer:          'অফার',
  ofer:           'অফার',
  sale:           'সেল',
  sell:           'সেল',
  buy:            'কেনা',
  price:          'দাম',
  cost:           'মূল্য',
  free:           'ফ্রি',
  cash:           'ক্যাশ',
  cashon:         'ক্যাশ অন ডেলিভারি',
  cod:            'ক্যাশ অন ডেলিভারি',
  return:         'রিটার্ন',
  refund:         'রিফান্ড',
  brand:          'ব্র্যান্ড',
  braend:         'ব্র্যান্ড',
  product:        'পণ্য',
  prodakt:        'পণ্য',
  item:           'আইটেম',
  stock:          'স্টক',
  warranty:       'ওয়ারেন্টি',
  waranti:        'ওয়ারেন্টি',
  review:         'রিভিউ',
  rivyu:          'রিভিউ',
  rating:         'রেটিং',
  reting:         'রেটিং',
  customer:       'গ্রাহক',
  service:        'সেবা',
  support:        'সাপোর্ট',
  helpline:       'হেল্পলাইন',
  online:         'অনলাইন',
  offline:        'অফলাইন',
  store:          'স্টোর',
  market:         'মার্কেট',
  marketplace:    'মার্কেটপ্লেস',

  // ── Fashion & Clothing ───────────────────────────────────────────────────
  jama:           'জামা',
  jaama:          'জামা',
  kapor:          'কাপড়',
  kapd:           'কাপড়',
  juta:           'জুতা',
  joota:          'জুতা',
  shoe:           'জুতা',
  shoes:          'জুতা',
  sandal:         'স্যান্ডেল',
  saendel:        'স্যান্ডেল',
  sneaker:        'স্নিকার',
  shirt:          'শার্ট',
  shart:          'শার্ট',
  tshirt:         'টি-শার্ট',
  pant:           'প্যান্ট',
  paent:          'প্যান্ট',
  pants:          'প্যান্ট',
  trouser:        'ট্রাউজার',
  jeans:          'জিন্স',
  saree:          'শাড়ি',
  shari:          'শাড়ি',
  sari:           'শাড়ি',
  salwar:         'সালোয়ার',
  kamiz:          'কামিজ',
  kameez:         'কামিজ',
  punjabi:        'পাঞ্জাবি',
  paijama:        'পায়জামা',
  pyjama:         'পায়জামা',
  lungi:          'লুঙ্গি',
  jacket:         'জ্যাকেট',
  jaeket:         'জ্যাকেট',
  coat:           'কোট',
  blazer:         'ব্লেজার',
  sweater:        'সোয়েটার',
  hoodie:         'হুডি',
  dress:          'ড্রেস',
  dres:           'ড্রেস',
  skirt:          'স্কার্ট',
  blouse:         'ব্লাউজ',
  kurta:          'কুর্তা',
  bag:            'ব্যাগ',
  baeg:           'ব্যাগ',
  backpack:       'ব্যাকপ্যাক',
  purse:          'পার্স',
  wallet:         'মানিব্যাগ',
  belt:           'বেল্ট',
  cap:            'ক্যাপ',
  hat:            'হ্যাট',
  watch:          'ঘড়ি',
  woch:           'ঘড়ি',
  ring:           'রিং',
  necklace:       'নেকলেস',
  bracelet:       'ব্রেসলেট',
  earring:        'কানের দুল',
  sunglasses:     'সানগ্লাস',
  glasses:        'চশমা',
  choshma:        'চশমা',
  perfume:        'পারফিউম',
  parfum:         'পারফিউম',
  socks:          'মোজা',
  moja:           'মোজা',
  underwear:      'আন্ডারওয়্যার',
  bra:            'ব্রা',
  makeup:         'মেকআপ',
  lipstick:       'লিপস্টিক',

  // ── Food & Grocery ───────────────────────────────────────────────────────
  rice:           'চাল',
  chal:           'চাল',
  vat:            'ভাত',
  dal:            'ডাল',
  daal:           'ডাল',
  fish:           'মাছ',
  mas:            'মাছ',
  maach:          'মাছ',
  meat:           'মাংস',
  mangsho:        'মাংস',
  chicken:        'মুরগি',
  murgi:          'মুরগি',
  beef:           'গরুর মাংস',
  mutton:         'খাসির মাংস',
  egg:            'ডিম',
  dim:            'ডিম',
  milk:           'দুধ',
  dudh:           'দুধ',
  oil:            'তেল',
  tel:            'তেল',
  sugar:          'চিনি',
  chini:          'চিনি',
  salt:           'লবণ',
  lobon:          'লবণ',
  bread:          'পাউরুটি',
  ruti:           'রুটি',
  water:          'পানি',
  pani:           'পানি',
  juice:          'জুস',
  tea:            'চা',
  cha:            'চা',
  coffee:         'কফি',
  milk2:          'দুধ',
  vegetable:      'সবজি',
  sobji:          'সবজি',
  sabji:          'সবজি',
  fruit:          'ফল',
  fol:            'ফল',
  tomato:         'টমেটো',
  potato:         'আলু',
  alu:            'আলু',
  onion:          'পেঁয়াজ',
  peyaj:          'পেঁয়াজ',
  garlic:         'রসুন',
  rosun:          'রসুন',
  ginger:         'আদা',
  ada:            'আদা',
  spice:          'মশলা',
  moshla:         'মশলা',
  biscuit:        'বিস্কুট',
  biskit:         'বিস্কুট',
  chocolate:      'চকলেট',
  chocolet:       'চকলেট',
  cake:           'কেক',
  icecream:       'আইসক্রিম',
  ice:            'বরফ',
  snack:          'স্ন্যাকস',
  chips:          'চিপস',
  noodles:        'নুডলস',
  pasta:          'পাস্তা',
  bread2:         'ব্রেড',

  // ── Home & Furniture ─────────────────────────────────────────────────────
  bari:           'বাড়ি',
  basa:           'বাসা',
  ghar:           'ঘর',
  gari:           'গাড়ি',
  car:            'গাড়ি',
  motor:          'মোটর',
  bike:           'বাইক',
  bicycle:        'সাইকেল',
  table:          'টেবিল',
  tebal:          'টেবিল',
  chair:          'চেয়ার',
  chear:          'চেয়ার',
  bed:            'বিছানা',
  bistar:         'বিছানা',
  sofa:           'সোফা',
  almirah:        'আলমারি',
  almari:         'আলমারি',
  wardrobe:       'ওয়ার্ডরোব',
  shelf:          'তাক',
  curtain:        'পর্দা',
  parda:          'পর্দা',
  carpet:         'কার্পেট',
  mat:            'মাদুর',
  pillow:         'বালিশ',
  balish:         'বালিশ',
  blanket:        'কম্বল',
  kambal:         'কম্বল',
  bedsheet:       'বেডশিট',
  towel:          'তোয়ালে',
  mirror:         'আয়না',
  ayna:           'আয়না',
  lamp:           'ল্যাম্প',
  bulb:           'বাল্ব',
  light:          'আলো',
  alo:            'আলো',
  lock:           'তালা',
  tala:           'তালা',
  kitchen:        'রান্নাঘর',
  cookware:       'রান্নার সরঞ্জাম',
  plate:          'থালা',
  thala:          'থালা',
  glass2:         'গ্লাস',
  pot:            'পাতিল',
  pan:            'কড়াই',

  // ── Health & Beauty ──────────────────────────────────────────────────────
  doctor:         'ডাক্তার',
  daktar:         'ডাক্তার',
  medicine:       'ওষুধ',
  oshud:          'ওষুধ',
  drug:           'ওষুধ',
  hospital:       'হাসপাতাল',
  health:         'স্বাস্থ্য',
  vitamin:        'ভিটামিন',
  supplement:     'সাপ্লিমেন্ট',
  protein:        'প্রোটিন',
  shampoo:        'শ্যাম্পু',
  shaepmpu:       'শ্যাম্পু',
  soap:           'সাবান',
  shabon:         'সাবান',
  lotion:         'লোশন',
  cream:          'ক্রিম',
  facewash:       'ফেসওয়াশ',
  moisturizer:    'ময়েশ্চারাইজার',
  sunscreen:      'সানস্ক্রিন',
  toothpaste:     'টুথপেস্ট',
  toothbrush:     'টুথব্রাশ',
  sanitizer:      'স্যানিটাইজার',
  mask:           'মাস্ক',
  haircolor:      'হেয়ার কালার',
  hairoil:        'হেয়ার অয়েল',

  // ── Education & Stationery ───────────────────────────────────────────────
  boi:            'বই',
  book:           'বই',
  notebook2:      'নোটবুক',
  pen:            'কলম',
  kalom:          'কলম',
  pencil:         'পেন্সিল',
  eraser:         'ইরেজার',
  scale:          'স্কেল',
  ruler:          'রুলার',
  scissors:       'কাঁচি',
  kachi:          'কাঁচি',
  glue:           'আঠা',
  ata:            'আঠা',
  tape:           'টেপ',
  paper:          'কাগজ',
  kagoj:          'কাগজ',
  envelope:       'খাম',
  khaam:          'খাম',

  // ── Common Bangla Words ──────────────────────────────────────────────────
  bangladesh:     'বাংলাদেশ',
  bangla:         'বাংলা',
  bangali:        'বাঙালি',
  bengali:        'বাঙালি',
  khabar:         'খবর',
  news:           'খবর',
  khobor:         'খবর',
  gaan:           'গান',
  shongeet:       'সংগীত',
  music2:         'সংগীত',
  cinema:         'সিনেমা',
  sinema:         'সিনেমা',
  film:           'চলচ্চিত্র',
  natok:          'নাটক',
  khela:          'খেলা',
  sports:         'খেলাধুলা',
  cricket:        'ক্রিকেট',
  football:       'ফুটবল',
  manush:         'মানুষ',
  desh:           'দেশ',
  shahor:         'শহর',
  shohore:        'শহর',
  gram:           'গ্রাম',
  ma:             'মা',
  baba:           'বাবা',
  ami:            'আমি',
  tumi:           'তুমি',
  apni:           'আপনি',
  amar:           'আমার',
  tomar:          'তোমার',
  khub:           'খুব',
  valo:           'ভালো',
  bhalo:          'ভালো',
  sundor:         'সুন্দর',
  dhakar:         'ঢাকার',
  dhaka:          'ঢাকা',
  chittagong:     'চট্টগ্রাম',
  sylhet:         'সিলেট',
  rajshahi:       'রাজশাহী',

  // ── Music & Entertainment ─────────────────────────────────────────────────
  music:          'মিউজিক',
  song:           'গান',
  video:          'ভিডিও',
  movie:          'মুভি',
  podcast:        'পডকাস্ট',
  streaming:      'স্ট্রিমিং',
  netflix:        'নেটফ্লিক্স',
  youtube:        'ইউটিউব',

  // ── Finance & Banking ─────────────────────────────────────────────────────
  bank:           'ব্যাংক',
  money:          'টাকা',
  taka:           'টাকা',
  loan:           'ঋণ',
  card:           'কার্ড',
  debit:          'ডেবিট',
  credit:         'ক্রেডিট',
  bkash:          'বিকাশ',
  nagad:          'নগদ',
  rocket:         'রকেট',
  upay:           'উপায়',
  insurance:      'বীমা',
  bima:           'বীমা',
  investment:     'বিনিয়োগ',

  // ── Real Estate & Construction ────────────────────────────────────────────
  flat:           'ফ্ল্যাট',
  apartment:      'অ্যাপার্টমেন্T',
  plot:           'প্লট',
  land:           'জমি',
  jomi:           'জমি',
  room:           'রুম',
  office:         'অফিস',
  building:       'ভবন',
  construction:   'নির্মাণ',
  rent:           'ভাড়া',
  bhara:          'ভাড়া',

  // ── Jobs & Career ─────────────────────────────────────────────────────────
  job:            'চাকরি',
  chakri:         'চাকরি',
  salary:         'বেতন',
  beton:          'বেতন',
  career:         'ক্যারিয়ার',
  interview:      'সাক্ষাৎকার',
  cv:             'সিভি',
  resume:         'রেজুমে',

  // ── Baby & Kids ──────────────────────────────────────────────────────────
  baby:           'শিশু',
  shishu:         'শিশু',
  kids:           'বাচ্চা',
  baccha:         'বাচ্চা',
  toy:            'খেলনা',
  khelna:         'খেলনা',
  diaper:         'ডায়াপার',
  'baby food':    'শিশু খাবার',
  stroller:       'স্ট্রলার',

  // ── Pet ──────────────────────────────────────────────────────────────────
  pet:            'পোষা প্রাণী',
  dog:            'কুকুর',
  kukur:          'কুকুর',
  cat:            'বিড়াল',
  biral:          'বিড়াল',
  bird:           'পাখি',
  pakhi:          'পাখি',
  petfood:        'পোষা প্রাণীর খাবার',

  // ── Discovery / Explore / General UI terms ────────────────────────────────
  discovery:      'ডিসকভারি',
  discover:       'ডিসকভার',
  explore:        'এক্সপ্লোর',
  collection:     'কালেকশন',
  category:       'ক্যাটাগরি',
  categories:     'ক্যাটাগরি',
  trending:       'ট্রেন্ডিং',
  featured:       'ফিচার্ড',
  popular:        'পপুলার',
  recommendation: 'রেকমেন্ডেশন',
  recommended:    'রেকমেন্ডেড',
  highlight:      'হাইলাইট',
  highlights:     'হাইলাইটস',
  banner:         'ব্যানার',
  feature:        'ফিচার',
  search:         'সার্চ',
  filter:         'ফিল্টার',
  sort:           'সর্ট',
  result:         'ফলাফল',
  results:        'ফলাফল',
  home:           'হোম',
  page:           'পেজ',
  dashboard:      'ড্যাশবোর্ড',
  profile:        'প্রোফাইল',
  account:        'অ্যাকাউন্ট',
  login:          'লগইন',
  logout:         'লগআউট',
  register:       'রেজিস্টার',
  signup:         'সাইনআপ',
  password:       'পাসওয়ার্ড',
  email:          'ইমেইল',
  notification:   'নোটিফিকেশন',
  cart:           'কার্ট',
  wishlist:       'উইশলিস্ট',
  checkout:       'চেকআউট',
  address:        'ঠিকানা',
  tracking:       'ট্র্যাকিং',
  track:          'ট্র্যাক',
  history:        'হিস্ট্রি',
  invoice:        'ইনভয়েস',

  // ── Product Qualifiers ─────────────────────────────────────────────────────
  new:            'নতুন',
  'new arrival':  'নতুন আসা',
  arrival:        'আগমন',
  latest:         'সর্বশেষ',
  hot:            'হট',
  top:            'টপ',
  best:           'সেরা',
  bestseller:     'বেস্টসেলার',
  premium:        'প্রিমিয়াম',
  luxury:         'লাক্সারি',
  quality:        'গুণমান',
  original:       'অরিজিনাল',
  genuine:        'জেনুইন',
  authentic:      'অথেনটিক',
  limited:        'সীমিত',
  exclusive:      'এক্সক্লুসিভ',
  available:      'পাওয়া যাচ্ছে',
  special:        'বিশেষ',
  unique:         'অনন্য',
  super:          'সুপার',
  mega:           'মেগা',
  ultra:          'আল্ট্রা',
  mini:           'মিনি',
  smart:          'স্মার্ট',
  digital:        'ডিজিটাল',
  automatic:      'অটোমেটিক',
  manual:         'ম্যানুয়াল',
  wireless:       'ওয়্যারলেস',
  waireles:       'ওয়্যারলেস',
  portable:       'পোর্টেবল',
  waterproof:     'ওয়াটারপ্রুফ',
  dustproof:      'ডাস্টপ্রুফ',
  shockproof:     'শকপ্রুফ',
  rechargeable:   'রিচার্জেবল',
  foldable:       'ফোল্ডেবল',
  adjustable:     'অ্যাডজাস্টেবল',
  durable:        'টেকসই',
  lightweight:    'হালকা',

  // ── Shipping / Delivery ────────────────────────────────────────────────────
  shipping:       'শিপিং',
  express:        'এক্সপ্রেস',
  standard:       'স্ট্যান্ডার্ড',
  fast:           'দ্রুত',
  quick:          'দ্রুত',
  same:           'একই',
  sameday:        'একদিনে ডেলিভারি',
  overnight:      'রাতারাতি',
  international:  'আন্তর্জাতিক',

  // ── Deals & Promotions ─────────────────────────────────────────────────────
  deal:           'ডিল',
  deals:          'ডিল',
  flash:          'ফ্ল্যাশ',
  promo:          'প্রমো',
  promotion:      'প্রমোশন',
  voucher:        'ভাউচার',
  coupon:         'কুপন',
  cashback:       'ক্যাশব্যাক',
  bundle:         'বান্ডেল',
  combo:          'কম্বো',
  pack:           'প্যাক',
  set:            'সেট',
  kit:            'কিট',
  gift:           'উপহার',
  giveaway:       'গিভঅ্যাওয়ে',

  // ── Tech / Specs ────────────────────────────────────────────────────────────
  ram:            'র‍্যাম',
  rom:            'রম',
  storage:        'স্টোরেজ',
  memory:         'মেমোরি',
  processor:      'প্রসেসর',
  gpu:            'জিপিইউ',
  display:        'ডিসপ্লে',
  screen:         'স্ক্রিন',
  resolution:     'রেজোলিউশন',
  pixel:          'পিক্সেল',
  megapixel:      'মেগাপিক্সেল',
  zoom:           'জুম',
  flash2:         'ফ্ল্যাশ',
  fingerprint:    'ফিঙ্গারপ্রিন্ট',
  faceunlock:     'ফেস আনলক',
  nfc:            'এনএফসি',
  usb:            'ইউএসবি',
  hdmi:           'এইচডিএমআই',
  type:           'টাইপ',
  version:        'ভার্সন',
  update:         'আপডেট',
  upgrade:        'আপগ্রেড',
  install:        'ইন্সটল',
  app:            'অ্যাপ',
  apps:           'অ্যাপস',
  download:       'ডাউনলোড',
  upload:         'আপলোড',
  cloud:          'ক্লাউড',
  backup:         'ব্যাকআপ',
  reset:          'রিসেট',
  repair:         'মেরামত',

  // ── Common English adjectives Avro mangles ────────────────────────────────
  old:            'পুরানো',
  used:           'ব্যবহৃত',
  second:         'দ্বিতীয়',
  secondhand:     'সেকেন্ডহ্যান্ড',
  refurbished:    'রিফার্বিশড',
  brand:          'ব্র্যান্ড',
  cheap:          'সস্তা',
  affordable:     'সাশ্রয়ী',
  expensive:      'দামি',
  price2:         'মূল্য',
  low:            'কম',
  high:           'বেশি',
  big:            'বড়',
  large:          'বড়',
  small:          'ছোট',
  medium:         'মাঝারি',
  heavy:          'ভারী',
  thin:           'পাতলা',
  thick:          'মোটা',
  long:           'লম্বা',
  short:          'ছোট',
  wide:           'প্রশস্ত',
  narrow:         'সংকীর্ণ',
  round:          'গোল',
  square:         'বর্গাকার',
  flat2:          'সমতল',
  curved:         'বাঁকানো',
  hard:           'শক্ত',
  soft:           'নরম',
  strong:         'শক্তিশালী',
  weak:           'দুর্বল',
  dark:           'গাঢ়',
  light2:         'হালকা',
  bright:         'উজ্জ্বল',
  color:          'রঙ',
  colour:         'রঙ',
  red:            'লাল',
  blue:           'নীল',
  green:          'সবুজ',
  yellow:         'হলুদ',
  black:          'কালো',
  white:          'সাদা',
  pink:           'গোলাপি',
  orange:         'কমলা',
  purple:         'বেগুনি',
  brown:          'বাদামি',
  golden:         'সোনালি',
  silver:         'রুপালি',
  transparent:    'স্বচ্ছ',
  matte:          'ম্যাট',
  glossy:         'চকচকে',

  // ── Common English words Avro mangles ─────────────────────────────────────
  channel:        'চ্যানেল',
  series:         'সিরিজ',
  season:         'সিজন',
  episode:        'এপিসোড',
  album:          'অ্যালবাম',
  concert:        'কনসার্ট',
  festival:       'উৎসব',
  event:          'ইভেন্ট',
  program:        'প্রোগ্রাম',
  class:          'ক্লাস',
  course:         'কোর্স',
  training:       'ট্রেনিং',
  tutorial:       'টিউটোরিয়াল',
  guide:          'গাইড',
  tips:           'টিপস',
  trick:          'ট্রিক',
  tricks:         'ট্রিকস',
  idea:           'আইডিয়া',
  ideas:          'আইডিয়া',
  review2:        'রিভিউ',
  unboxing:       'আনবক্সিং',
  compare:        'তুলনা',
  comparison:     'তুলনা',
  alternative:    'বিকল্প',
  solution:       'সমাধান',
  problem:        'সমস্যা',
  issue:          'সমস্যা',
  error:          'এরর',
  fix:            'ঠিক করা',
  help:           'সাহায্য',
  contact:        'যোগাযোগ',
  feedback:       'ফিডব্যাক',
  complaint:      'অভিযোগ',
  report:         'রিপোর্ট',

  // ── Sports ────────────────────────────────────────────────────────────────
  jersey:         'জার্সি',
  tournament:     'টুর্নামেন্ট',
  league:         'লিগ',
  team:           'দল',
  player:         'খেলোয়াড়',
  gym:            'জিম',
  fitness:        'ফিটনেস',
  yoga:           'যোগব্যায়াম',
  exercise:       'ব্যায়াম',
  treadmill:      'ট্রেডমিল',
  dumbbell:       'ডাম্বেল',
  protein2:       'প্রোটিন',
  equipment:      'সরঞ্জাম',
};

// ─── Normalise a lookup key ────────────────────────────────────────────────
function normKey(w: string): string {
  return w.toLowerCase().trim();
}

// ─── Core lookup (with common English plural / suffix stripping) ───────────
function lookupWord(word: string): string | null {
  const k = normKey(word);
  if (WORD_DICT[k]) return WORD_DICT[k];

  // Try stripping English plurals / common suffixes
  const suffixes = ['ing', 'ers', 'es', 's', 'ed', 'er'];
  for (const sfx of suffixes) {
    if (k.endsWith(sfx) && k.length - sfx.length >= 3) {
      const stem = k.slice(0, k.length - sfx.length);
      if (WORD_DICT[stem]) return WORD_DICT[stem];
    }
  }
  return null;
}

// ─── Public API ───────────────────────────────────────────────────────────

/**
 * Transliterate a single whitespace-free word.
 * Tries the dictionary first; falls back to Avro phonetic.
 */
export function transliterateWord(word: string): string {
  if (!word.trim()) return word;
  const hit = lookupWord(word);
  if (hit) return hit;
  // Avro phonetic fallback
  return avroParse(word);
}

/**
 * Transliterate a full phrase / sentence word-by-word.
 * Whitespace tokens are preserved unchanged.
 */
export function transliterateText(text: string): string {
  if (!text.trim()) return text;
  return text
    .split(/(\s+)/)
    .map(token => (/^\s+$/.test(token) ? token : transliterateWord(token)))
    .join('');
}

/**
 * Return dictionary suggestions for an incomplete word (prefix search).
 * @param partial  - what the user has typed so far
 * @param limit    - maximum results (default 6)
 * Returns array of { en, bn } pairs sorted by key length (shortest first).
 */
export function getSuggestions(
  partial: string,
  limit = 6,
): Array<{ en: string; bn: string }> {
  const k = normKey(partial);
  if (k.length < 2) return [];

  return Object.entries(WORD_DICT)
    .filter(([key]) => key.startsWith(k))
    .sort((a, b) => a[0].length - b[0].length)
    .slice(0, limit)
    .map(([en, bn]) => ({ en, bn }));
}

/** Alias: matches the API surface requested in the requirements. */
export const convertBanglishToBangla = transliterateText;

/** Alias: short form. */
export const transliterate = transliterateText;

/**
 * Given a raw user query and inputMode, return the terms to send to the
 * search backend:
 *   - q:    the primary search term (Bangla if BN mode, else raw)
 *   - qEn:  the original English term to also search (only in BN mode)
 */
export function buildSearchTerms(
  raw: string,
  inputMode: 'BN' | 'EN',
): { q: string; qEn?: string } {
  if (inputMode !== 'BN' || !raw.trim()) return { q: raw };
  const bn = transliterateText(raw.trim());
  const q = bn !== raw.trim() ? bn : raw;
  return { q, qEn: raw.trim() };
}
