import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
    en: {
        // Header & Navigation
        searchPlaceholder: "Search your products...",
        deliveryLocation: "Select your delivery location",
        downloadApp: "Download App Now",
        signIn: "Sign In / Sign up",
        account: "Account",
        cart: "Cart",
        items: "Items",
        item: "item",
        shopByCategory: "SHOP BY CATEGORY",
        topCategories: "Top Categories",
        allCategories: "ALL CATEGORIES",

        // Product Related
        addToBag: "Add to Bag",
        addToBagBtn: "+ Add to Bag",
        addToCart: "Add to Cart",
        delivery: "Delivery",
        perPiece: "Per Piece",
        hot: "HOT",
        new: "NEW",
        sale: "SALE",
        off: "OFF",
        outOfStock: "Out of Stock",
        inStock: "In Stock",
        discount: "Discount",
        delivery12Hours: "Delivery 1-2 hours",
        adding: "Adding...",

        // Timing
        hours: "hours",
        minutes: "minutes",
        seconds: "seconds",

        // Sections
        freshProduce: "FRESH PRODUCE",
        greatDeals: "GREAT DEALS",
        snacksBeverages: "SNACKS & BEVERAGES",
        ourBrands: "OUR BRANDS",
        household: "HOUSEHOLD",
        personalCare: "PERSONAL CARE",
        recommendedProducts: "Recommended For You",
        trendingProducts: "Trending Products",
        featuredProducts: "Featured Products",
        bestDeals: "Best Deals",
        newArrivals: "New Arrivals",

        // Features
        freeDelivery: "Free Delivery",
        freeDeliveryDesc: "On orders above ৳500",
        securePayment: "Secure Payment",
        securePaymentDesc: "100% secure payment",
        easyReturns: "Easy Returns",
        easyReturnsDesc: "7 days return policy",
        support247: "24/7 Support",
        support247Desc: "Dedicated support",

        // Footer
        ourOutlets: "Our Outlets",
        helpLine: "Help Line",
        aboutUs: "About Us",
        contactUs: "Contact Us",
        termsConditions: "Terms & Conditions",
        privacyPolicy: "Privacy Policy",
        careers: "Careers",
        blog: "Blog",
        customerService: "Customer Service",
        myAccount: "My Account",
        trackOrder: "Track Order",
        offers: "Offers",
        help: "Help",
        faq: "FAQ",
        deliveryAreas: "Delivery Areas",
        returnPolicy: "Return Policy",
        shippingInfo: "Shipping Info",
        sellOnSholok: "Sell on Sholok",
        sholokTagline: "Your trusted online grocery shopping destination. Fresh products delivered to your doorstep.",

        // Modal
        locationHeader: "Delivery Location",
        searchLocation: "Road 6, Block C",
        or: "OR",
        selectDistrict: "Select district",
        selectArea: "Select area",
        done: "Done",
        close: "Close",

        // Buttons & Actions
        viewAll: "View All",
        buyNow: "Buy Now",
        quickView: "Quick View",
        compare: "Compare",
        addToWishlist: "Add to Wishlist",
        clearAll: "Clear All",
        applyFilters: "Apply Filters",
        continueShopping: "Continue Shopping",
        proceedToCheckout: "Proceed to Checkout",

        // Messages
        addedToCart: "Added to cart!",
        addedToWishlist: "Added to wishlist",
        removedFromWishlist: "Removed from wishlist",
        loginToWishlist: "Please login to add to wishlist",
        failedToAddToCart: "Failed to add to cart",
        failedToUpdateWishlist: "Failed to update wishlist",

        // Search
        trending: "Trending",
        popularSearches: "Popular Searches",
        categories: "Categories",
        brands: "Brands",
        searchAnyway: "Search anyway →",
        noResultsFound: "No results found",

        // Filter Sidebar
        filters: "Filters",
        priceRange: "Price Range",
        customerRatings: "Customer Ratings",
        andAbove: "& above",
        discount10: "10% or more",
        discount20: "20% or more",
        discount30: "30% or more",
        discount50: "50% or more",

        // Cart
        shoppingCart: "Shopping Cart",
        subtotal: "Subtotal",
        deliveryFee: "Delivery Fee",
        total: "Total",
        emptyCart: "Your cart is empty",
        startShopping: "Start Shopping",

        // Auth
        login: "Login",
        register: "Register",
        logout: "Logout",
        email: "Email",
        password: "Password",
        forgotPassword: "Forgot Password?",
        welcomeBack: "Welcome Back",
        loginToContinue: "Login to your account to continue shopping",
        rememberMe: "Remember me",
        loggingIn: "Logging in...",
        loginSuccess: "Login successful!",
        noAccount: "Don't have an account?",
        areYouVendor: "Are you a vendor?",
        signInVendorPanel: "Sign in to Vendor Panel",

        // Register
        createAccount: "Create Account",
        registerToShop: "Register to start shopping with us",
        fullName: "Full Name",
        phoneNumber: "Phone Number",
        confirmPassword: "Confirm Password",
        creatingAccount: "Creating account...",
        passwordsDoNotMatch: "Passwords do not match",
        passwordTooShort: "Password must be at least 6 characters",
        registrationSuccess: "Registration successful!",
        alreadyHaveAccount: "Already have an account?",

        // Forgot Password
        forgotPasswordTitle: "Forgot Password",
        enterVerificationCode: "Enter Verification Code",
        setNewPassword: "Set New Password",
        forgotPasswordDesc: "Enter your email address and we will send you a verification code",
        createNewPassword: "Create a new password for your account",
        verificationCode: "Verification Code",
        newPassword: "New Password",
        sendVerificationCode: "Send Verification Code",
        verifyCode: "Verify Code",
        resetPassword: "Reset Password",
        sending: "Sending...",
        verifying: "Verifying...",
        resetting: "Resetting...",
        rememberPassword: "Remember your password?",
        backToLogin: "Back to Login",
        didntReceiveCode: "Didn't receive the code? Resend",
        pleaseEnterEmail: "Please enter your email",
        pleaseEnterCode: "Please enter the verification code",
        codeSent: "Verification code sent!",
        codeVerified: "Code verified!",
        passwordResetSuccess: "Password reset successfully! Please login.",
        failedToSendCode: "Failed to send code",
        invalidCode: "Invalid code",
        failedToResetPassword: "Failed to reset password",

        // Checkout
        checkout: "Checkout",
        shippingFee: "Shipping Fee",
        proceed: "Proceed",
        pleaseLoginToCheckout: "Please Login to Checkout",
        needSignedIn: "You need to be signed in to place an order.",
        yourCartIsEmpty: "Your Cart is Empty",
        shippingAddress: "Shipping Address",
        address: "Address",
        city: "City",
        areaThana: "Area / Thana",
        groceryDeliverySchedule: "Grocery Delivery Schedule",
        deliveryDate: "Delivery Date",
        today: "Today",
        tomorrow: "Tomorrow",
        selectTimeSlot: "Select Time Slot",
        paymentMethod: "Payment Method",
        cashOnDelivery: "Cash on Delivery",
        cardPayment: "Card / Online Payment",
        haveCoupon: "Have a coupon?",
        enterCouponCode: "Enter coupon code",
        apply: "Apply",
        remove: "Remove",
        orderSummary: "Order Summary",
        placeOrder: "Place Order",
        placingOrder: "Placing Order...",
        couponApplied: "Coupon Applied",
        couponDiscount: "Coupon Discount",
        orderPlacedSuccess: "Order placed successfully!",
        failedToPlaceOrder: "Failed to place order",
        cartIsEmpty: "Your cart is empty",
        nameRequired: "Name is required",
        phoneRequired: "Phone is required",
        addressRequired: "Address is required",
        cityRequired: "City is required",
        areaRequired: "Area is required",

        // Account Page
        pleaseLogin: "Please Login",
        needLoginToAccess: "You need to login to access your account",
        loginNow: "Login Now",
        dashboard: "Dashboard",
        myOrders: "My Orders",
        wishlist: "Wishlist",
        addresses: "Addresses",
        rewards: "Rewards",
        reviews: "Reviews",
        notifications: "Notifications",
        settings: "Settings",
        recentOrders: "Recent Orders",
        viewAllOrders: "View All Orders",
        noOrders: "No orders yet",
        noWishlistItems: "No wishlist items",
        noAddresses: "No saved addresses",
        noReviews: "No reviews yet",
        noNotifications: "No notifications",
        orderCancelledSuccess: "Order cancelled successfully",
        failedToCancelOrder: "Failed to cancel order",
        profileUpdated: "Profile updated",
        failedToUpdateProfile: "Failed to update profile",
        addressUpdated: "Address updated",
        failedToUpdateAddress: "Failed to update address",
        addressAdded: "Address added",
        failedToSaveAddress: "Failed to save address",
        addressDeleted: "Address deleted",
        failedToDeleteAddress: "Failed to delete address",
        defaultAddressUpdated: "Default address updated",
        passwordChanged: "Password changed successfully",
        failedToChangePassword: "Failed to change password",
        allNotificationsRead: "All notifications marked as read",
        failedToUpdateNotifications: "Failed to update notifications",
        removedFromWishlistSuccess: "Removed from wishlist",
        failedToRemoveFromWishlist: "Failed to remove from wishlist",
        failedToLoadOrders: "Failed to load orders",
        failedToLoadAddresses: "Failed to load addresses",
        failedToLoadWishlist: "Failed to load wishlist",
        failedToLoadRewards: "Failed to load rewards",
        failedToLoadReviews: "Failed to load reviews",
        failedToLoadNotifications: "Failed to load notifications",
        cancelOrder: "Cancel Order",
        confirmCancel: "Are you sure you want to cancel this order?",
        yes: "Yes",
        no: "No",
        currentPassword: "Current Password",
        changePassword: "Change Password",
        save: "Save",
        cancel: "Cancel",
        edit: "Edit",
        delete: "Delete",
        addAddress: "Add Address",
        setAsDefault: "Set as Default",
        default: "Default",
        markAllRead: "Mark All Read",
        printInvoice: "Print Invoice",
        trackShipment: "Track Shipment",

        // Mobile Nav
        home: "Home",

        // Homepage Section Titles
        breadAndMore: "Bread & More",
        unileverWeek: "Unilever Week",
        unileverMegaSaleTitle: "UNILEVER MEGA SALE",
        upTo80Off: "UP TO 80% OFF",
        voucherUBL: "৳100 Voucher on ৳1000+ - VOUCHER: UBL100",
        weekdayDeals: "Weekday Deals!!!",
        cleaningEssentials: "Everyday Cleaning Essentials",
        snacksAndSweets: "🍪 Snacks & Sweets 🍫",
        todaysFeaturedFinds: "Today's Featured Finds",
        spiceUpCookingTitle: "🌶️ Spice Up Your Cooking Game",
        happyHourTitle: "Happy Hour",
        freshVegetablesFruitsTitle: "🥬 Fresh Vegetables & Fruits 🍎",
        beveragesTitle: "🥤 Beverages ☕",
        frozenFoodsTitle: "🧊 Frozen Foods 🍦",
        gadgetsElectronicsTitle: "📱 Gadgets & Electronics 💻",
        festivalBannerTitle: "Festival Special Offers!",
        festivalBannerSubtitle: "Save up to 50% on fresh groceries & more",

        // Feature Cards
        minsDelivery: "60 Mins Delivery",
        freeShippingOver: "Free shipping over ৳1000",
        authorizedProducts: "Authorized Products",
        hundredAuthentic: "100% Authentic",
        customerSupportLabel: "Customer Support",
        supportHoursLabel: "8am - 10pm",
        flexiblePayments: "Flexible Payments",
        paymentMethods: "Credit Cards & Mobile Banking",

        // Fresh Vegetables Tabs
        freshVegetablesTab: "Fresh Vegetables",
        eggsCerealsTab: "Eggs & Cereals",
        frozenSnacksTab: "Frozen Snacks",
        diabeticCornerTab: "Diabetic Corner",

        // Weekday Deals Tabs
        noodlesTab: "Noodles",
        pastaTab: "Pasta",
        fullCreamMilkTab: "Full Cream Milk",
        regularSpiceTab: "Regular Spice",
        biscuitsOthersTab: "Biscuits Others",
        flavouredTeaTab: "Flavored Tea",
        teaEtcTab: "Tea Etc",

        // Empty States
        noProductsCategory: "No products available in this category yet.",
        checkBackSnacks: "Check back soon for delicious snacks and sweets!",
        productsComing: "Products coming soon!",
        noBeverages: "No beverages available yet.",
        beveragesComing: "Coming soon: Tea, Coffee, Juice and more!",
        noFrozenFoods: "No frozen foods available yet.",
        frozenComing: "Coming soon: Ice cream, Frozen vegetables and more!",
        noGadgets: "No gadgets available yet.",
        gadgetsComing: "Coming soon: Mobile accessories, Smart devices and more!",

        // Vendor Apply Page
        vendorApplyTitle: "Become a Vendor",
        vendorApplyDesc: "Join our marketplace and start selling",

        // Track Order
        trackOrderTitle: "Track Your Order",
        enterOrderNumber: "Enter Order Number",
        track: "Track",
    },
    bn: {
        // Header & Navigation
        searchPlaceholder: "আপনার পণ্য অনুসন্ধান করুন...",
        deliveryLocation: "আপনার ডেলিভারি অবস্থান নির্বাচন করুন",
        downloadApp: "অ্যাপ ডাউনলোড করুন",
        signIn: "সাইন ইন / সাইন আপ",
        account: "অ্যাকাউন্ট",
        cart: "কার্ট",
        items: "আইটেম",
        item: "আইটেম",
        shopByCategory: "ক্যাটাগরি অনুযায়ী কিনুন",
        topCategories: "জনপ্রিয় ক্যাটাগরি",
        allCategories: "সকল ক্যাটাগরি",

        // Product Related
        addToBag: "ব্যাগে যোগ করুন",
        addToBagBtn: "+ ব্যাগে যোগ করুন",
        addToCart: "কার্টে যোগ করুন",
        delivery: "ডেলিভারি",
        perPiece: "প্রতি পিস",
        hot: "হট",
        new: "নতুন",
        sale: "সেল",
        off: "ছাড়",
        outOfStock: "স্টক শেষ",
        inStock: "স্টকে আছে",
        discount: "ছাড়",
        delivery12Hours: "ডেলিভারি ১-২ ঘন্টা",
        adding: "যোগ হচ্ছে...",

        // Timing
        hours: "ঘন্টা",
        minutes: "মিনিট",
        seconds: "সেকেন্ড",

        // Sections
        freshProduce: "তাজা পণ্য",
        greatDeals: "সেরা ডিল",
        snacksBeverages: "স্ন্যাকস ও পানীয়",
        ourBrands: "আমাদের ব্র্যান্ড",
        household: "গৃহস্থালী",
        personalCare: "ব্যক্তিগত যত্ন",
        recommendedProducts: "আপনার জন্য সুপারিশকৃত",
        trendingProducts: "ট্রেন্ডিং পণ্য",
        featuredProducts: "বিশেষ পণ্য",
        bestDeals: "সেরা অফার",
        newArrivals: "নতুন আগমন",

        // Features
        freeDelivery: "ফ্রি ডেলিভারি",
        freeDeliveryDesc: "৳৫০০ এর উপরে অর্ডারে",
        securePayment: "নিরাপদ পেমেন্ট",
        securePaymentDesc: "১০০% নিরাপদ পেমেন্ট",
        easyReturns: "সহজ রিটার্ন",
        easyReturnsDesc: "৭ দিনের রিটার্ন পলিসি",
        support247: "২৪/৭ সাপোর্ট",
        support247Desc: "ডেডিকেটেড সাপোর্ট",

        // Footer
        ourOutlets: "আমাদের আউটলেট",
        helpLine: "হেল্প লাইন",
        aboutUs: "আমাদের সম্পর্কে",
        contactUs: "যোগাযোগ",
        termsConditions: "শর্তাবলী",
        privacyPolicy: "গোপনীয়তা নীতি",
        careers: "ক্যারিয়ার",
        blog: "ব্লগ",
        customerService: "গ্রাহক সেবা",
        myAccount: "আমার অ্যাকাউন্ট",
        trackOrder: "অর্ডার ট্র্যাক করুন",
        offers: "অফার",
        help: "সাহায্য",
        faq: "সাধারণ প্রশ্নোত্তর",
        deliveryAreas: "ডেলিভারি এলাকা",
        returnPolicy: "রিটার্ন পলিসি",
        shippingInfo: "শিপিং তথ্য",
        sellOnSholok: "শলোকে বিক্রি করুন",
        sholokTagline: "আপনার বিশ্বস্ত অনলাইন মুদিখানা। তাজা পণ্য আপনার দরজায় পৌঁছে দেওয়া হবে।",

        // Modal
        locationHeader: "ডেলিভারি অবস্থান",
        searchLocation: "রোড ৬, ব্লক সি",
        or: "অথবা",
        selectDistrict: "জেলা নির্বাচন করুন",
        selectArea: "এলাকা নির্বাচন করুন",
        done: "সম্পন্ন",
        close: "বন্ধ করুন",

        // Buttons & Actions
        viewAll: "সব দেখুন",
        buyNow: "এখনই কিনুন",
        quickView: "দ্রুত দেখুন",
        compare: "তুলনা করুন",
        addToWishlist: "উইশলিস্টে যোগ করুন",
        clearAll: "সব মুছুন",
        applyFilters: "ফিল্টার প্রয়োগ করুন",
        continueShopping: "কেনাকাটা চালিয়ে যান",
        proceedToCheckout: "চেকআউটে যান",

        // Messages
        addedToCart: "কার্টে যোগ করা হয়েছে!",
        addedToWishlist: "উইশলিস্টে যোগ করা হয়েছে",
        removedFromWishlist: "উইশলিস্ট থেকে সরানো হয়েছে",
        loginToWishlist: "উইশলিস্টে যোগ করতে লগইন করুন",
        failedToAddToCart: "কার্টে যোগ করতে ব্যর্থ হয়েছে",
        failedToUpdateWishlist: "উইশলিস্ট আপডেট করতে ব্যর্থ হয়েছে",

        // Search
        trending: "ট্রেন্ডিং",
        popularSearches: "জনপ্রিয় সার্চ",
        categories: "ক্যাটাগরি",
        brands: "ব্র্যান্ড",
        searchAnyway: "তবুও সার্চ করুন →",
        noResultsFound: "কোন পণ্য পাওয়া যায়নি",

        // Filter Sidebar
        filters: "ফিল্টার",
        priceRange: "মূল্য পরিসীমা",
        customerRatings: "গ্রাহক রেটিং",
        andAbove: "ও তার বেশি",
        discount10: "১০% বা তার বেশি",
        discount20: "২০% বা তার বেশি",
        discount30: "৩০% বা তার বেশি",
        discount50: "৫০% বা তার বেশি",

        // Cart
        shoppingCart: "শপিং কার্ট",
        subtotal: "সাবটোটাল",
        deliveryFee: "ডেলিভারি ফি",
        total: "মোট",
        emptyCart: "আপনার কার্ট খালি",
        startShopping: "কেনাকাটা শুরু করুন",

        // Auth
        login: "লগইন",
        register: "রেজিস্টার",
        logout: "লগআউট",
        email: "ইমেইল",
        password: "পাসওয়ার্ড",
        forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
        welcomeBack: "স্বাগতম",
        loginToContinue: "কেনাকাটা চালিয়ে যেতে আপনার অ্যাকাউন্টে লগইন করুন",
        rememberMe: "মনে রাখুন",
        loggingIn: "লগইন হচ্ছে...",
        loginSuccess: "লগইন সফল হয়েছে!",
        noAccount: "অ্যাকাউন্ট নেই?",
        areYouVendor: "আপনি কি বিক্রেতা?",
        signInVendorPanel: "ভেন্ডর প্যানেলে সাইন ইন করুন",

        // Register
        createAccount: "অ্যাকাউন্ট তৈরি করুন",
        registerToShop: "কেনাকাটা শুরু করতে রেজিস্টার করুন",
        fullName: "পুরো নাম",
        phoneNumber: "ফোন নম্বর",
        confirmPassword: "পাসওয়ার্ড নিশ্চিত করুন",
        creatingAccount: "অ্যাকাউন্ট তৈরি হচ্ছে...",
        passwordsDoNotMatch: "পাসওয়ার্ড মিলছে না",
        passwordTooShort: "পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে",
        registrationSuccess: "রেজিস্ট্রেশন সফল হয়েছে!",
        alreadyHaveAccount: "ইতোমধ্যে অ্যাকাউন্ট আছে?",

        // Forgot Password
        forgotPasswordTitle: "পাসওয়ার্ড ভুলে গেছেন",
        enterVerificationCode: "যাচাইকরণ কোড দিন",
        setNewPassword: "নতুন পাসওয়ার্ড সেট করুন",
        forgotPasswordDesc: "আপনার ইমেইল ঠিকানা দিন, আমরা একটি যাচাইকরণ কোড পাঠাব",
        createNewPassword: "আপনার অ্যাকাউন্টের জন্য নতুন পাসওয়ার্ড তৈরি করুন",
        verificationCode: "যাচাইকরণ কোড",
        newPassword: "নতুন পাসওয়ার্ড",
        sendVerificationCode: "যাচাইকরণ কোড পাঠান",
        verifyCode: "কোড যাচাই করুন",
        resetPassword: "পাসওয়ার্ড রিসেট করুন",
        sending: "পাঠানো হচ্ছে...",
        verifying: "যাচাই হচ্ছে...",
        resetting: "রিসেট হচ্ছে...",
        rememberPassword: "পাসওয়ার্ড মনে আছে?",
        backToLogin: "লগইনে ফিরে যান",
        didntReceiveCode: "কোড পাননি? পুনরায় পাঠান",
        pleaseEnterEmail: "আপনার ইমেইল দিন",
        pleaseEnterCode: "যাচাইকরণ কোড দিন",
        codeSent: "যাচাইকরণ কোড পাঠানো হয়েছে!",
        codeVerified: "কোড যাচাই হয়েছে!",
        passwordResetSuccess: "পাসওয়ার্ড সফলভাবে রিসেট হয়েছে! লগইন করুন।",
        failedToSendCode: "কোড পাঠাতে ব্যর্থ হয়েছে",
        invalidCode: "অবৈধ কোড",
        failedToResetPassword: "পাসওয়ার্ড রিসেট করতে ব্যর্থ হয়েছে",

        // Checkout
        checkout: "চেকআউট",
        shippingFee: "শিপিং ফি",
        proceed: "এগিয়ে যান",
        pleaseLoginToCheckout: "চেকআউট করতে লগইন করুন",
        needSignedIn: "অর্ডার দিতে আপনাকে সাইন ইন করতে হবে।",
        yourCartIsEmpty: "আপনার কার্ট খালি",
        shippingAddress: "শিপিং ঠিকানা",
        address: "ঠিকানা",
        city: "শহর",
        areaThana: "এলাকা / থানা",
        groceryDeliverySchedule: "মুদিখানা ডেলিভারি সময়সূচী",
        deliveryDate: "ডেলিভারি তারিখ",
        today: "আজ",
        tomorrow: "আগামীকাল",
        selectTimeSlot: "সময় স্লট নির্বাচন করুন",
        paymentMethod: "পেমেন্ট পদ্ধতি",
        cashOnDelivery: "ক্যাশ অন ডেলিভারি",
        cardPayment: "কার্ড / অনলাইন পেমেন্ট",
        haveCoupon: "কুপন আছে?",
        enterCouponCode: "কুপন কোড দিন",
        apply: "প্রয়োগ করুন",
        remove: "সরান",
        orderSummary: "অর্ডার সারাংশ",
        placeOrder: "অর্ডার করুন",
        placingOrder: "অর্ডার হচ্ছে...",
        couponApplied: "কুপন প্রয়োগ হয়েছে",
        couponDiscount: "কুপন ছাড়",
        orderPlacedSuccess: "অর্ডার সফলভাবে দেওয়া হয়েছে!",
        failedToPlaceOrder: "অর্ডার দিতে ব্যর্থ হয়েছে",
        cartIsEmpty: "আপনার কার্ট খালি",
        nameRequired: "নাম আবশ্যক",
        phoneRequired: "ফোন নম্বর আবশ্যক",
        addressRequired: "ঠিকানা আবশ্যক",
        cityRequired: "শহর আবশ্যক",
        areaRequired: "এলাকা আবশ্যক",

        // Account Page
        pleaseLogin: "লগইন করুন",
        needLoginToAccess: "আপনার অ্যাকাউন্ট দেখতে লগইন করতে হবে",
        loginNow: "এখনই লগইন করুন",
        dashboard: "ড্যাশবোর্ড",
        myOrders: "আমার অর্ডার",
        wishlist: "উইশলিস্ট",
        addresses: "ঠিকানাসমূহ",
        rewards: "পুরস্কার",
        reviews: "রিভিউ",
        notifications: "বিজ্ঞপ্তি",
        settings: "সেটিংস",
        recentOrders: "সাম্প্রতিক অর্ডার",
        viewAllOrders: "সব অর্ডার দেখুন",
        noOrders: "এখনো কোন অর্ডার নেই",
        noWishlistItems: "উইশলিস্টে কিছু নেই",
        noAddresses: "কোন সংরক্ষিত ঠিকানা নেই",
        noReviews: "এখনো কোন রিভিউ নেই",
        noNotifications: "কোন বিজ্ঞপ্তি নেই",
        orderCancelledSuccess: "অর্ডার সফলভাবে বাতিল হয়েছে",
        failedToCancelOrder: "অর্ডার বাতিল করতে ব্যর্থ হয়েছে",
        profileUpdated: "প্রোফাইল আপডেট হয়েছে",
        failedToUpdateProfile: "প্রোফাইল আপডেট করতে ব্যর্থ হয়েছে",
        addressUpdated: "ঠিকানা আপডেট হয়েছে",
        failedToUpdateAddress: "ঠিকানা আপডেট করতে ব্যর্থ হয়েছে",
        addressAdded: "ঠিকানা যোগ হয়েছে",
        failedToSaveAddress: "ঠিকানা সংরক্ষণ করতে ব্যর্থ হয়েছে",
        addressDeleted: "ঠিকানা মুছে গেছে",
        failedToDeleteAddress: "ঠিকানা মুছতে ব্যর্থ হয়েছে",
        defaultAddressUpdated: "ডিফল্ট ঠিকানা আপডেট হয়েছে",
        passwordChanged: "পাসওয়ার্ড সফলভাবে পরিবর্তন হয়েছে",
        failedToChangePassword: "পাসওয়ার্ড পরিবর্তন করতে ব্যর্থ হয়েছে",
        allNotificationsRead: "সব বিজ্ঞপ্তি পড়া হয়েছে হিসেবে চিহ্নিত",
        failedToUpdateNotifications: "বিজ্ঞপ্তি আপডেট করতে ব্যর্থ হয়েছে",
        removedFromWishlistSuccess: "উইশলিস্ট থেকে সরানো হয়েছে",
        failedToRemoveFromWishlist: "উইশলিস্ট থেকে সরাতে ব্যর্থ হয়েছে",
        failedToLoadOrders: "অর্ডার লোড করতে ব্যর্থ হয়েছে",
        failedToLoadAddresses: "ঠিকানা লোড করতে ব্যর্থ হয়েছে",
        failedToLoadWishlist: "উইশলিস্ট লোড করতে ব্যর্থ হয়েছে",
        failedToLoadRewards: "পুরস্কার লোড করতে ব্যর্থ হয়েছে",
        failedToLoadReviews: "রিভিউ লোড করতে ব্যর্থ হয়েছে",
        failedToLoadNotifications: "বিজ্ঞপ্তি লোড করতে ব্যর্থ হয়েছে",
        cancelOrder: "অর্ডার বাতিল করুন",
        confirmCancel: "আপনি কি নিশ্চিতভাবে এই অর্ডার বাতিল করতে চান?",
        yes: "হ্যাঁ",
        no: "না",
        currentPassword: "বর্তমান পাসওয়ার্ড",
        changePassword: "পাসওয়ার্ড পরিবর্তন করুন",
        save: "সংরক্ষণ করুন",
        cancel: "বাতিল",
        edit: "সম্পাদনা",
        delete: "মুছুন",
        addAddress: "ঠিকানা যোগ করুন",
        setAsDefault: "ডিফল্ট হিসেবে সেট করুন",
        default: "ডিফল্ট",
        markAllRead: "সব পড়া হয়েছে হিসেবে চিহ্নিত করুন",
        printInvoice: "ইনভয়েস প্রিন্ট করুন",
        trackShipment: "শিপমেন্ট ট্র্যাক করুন",

        // Mobile Nav
        home: "হোম",

        // Homepage Section Titles
        breadAndMore: "রুটি ও আরো",
        unileverWeek: "ইউনিলিভার সপ্তাহ",
        unileverMegaSaleTitle: "ইউনিলিভার মেলা",
        upTo80Off: "৮০% পর্যন্ত ছাড়",
        voucherUBL: "১০০০ টাকার উপরে ১০০ টাকা ভাউচার - VOUCHER: UBL100",
        weekdayDeals: "সাপ্তাহিক ডিল!!!",
        cleaningEssentials: "প্রতিদিনের পরিষ্কার পণ্য",
        snacksAndSweets: "🍪 স্ন্যাকস ও মিষ্টি 🍫",
        todaysFeaturedFinds: "আজকের বিশেষ পণ্য",
        spiceUpCookingTitle: "🌶️ রান্নাঘরকে মশলাদার করুন",
        happyHourTitle: "হ্যাপি আওয়ার",
        freshVegetablesFruitsTitle: "🥬 তাজা শাকসবজি ও ফল 🍎",
        beveragesTitle: "🥤 পানীয় ☕",
        frozenFoodsTitle: "🧊 ফ্রোজেন ফুড 🍦",
        gadgetsElectronicsTitle: "📱 গ্যাজেট ও ইলেকট্রনিক্স 💻",
        festivalBannerTitle: "উৎসব বিশেষ অফার!",
        festivalBannerSubtitle: "তাজা মুদিখানায় ৫০% পর্যন্ত সাশ্রয় করুন",

        // Feature Cards
        minsDelivery: "৬০ মিনিট ডেলিভারি",
        freeShippingOver: "৳১০০০ এর উপরে ফ্রি শিপিং",
        authorizedProducts: "অনুমোদিত পণ্য",
        hundredAuthentic: "১০০% খাঁটি",
        customerSupportLabel: "গ্রাহক সেবা",
        supportHoursLabel: "সকাল ৮টা - রাত ১০টা",
        flexiblePayments: "নমনীয় পেমেন্ট",
        paymentMethods: "ক্রেডিট কার্ড ও মোবাইল ব্যাংকিং",

        // Fresh Vegetables Tabs
        freshVegetablesTab: "তাজা শাকসবজি",
        eggsCerealsTab: "ডিম ও সিরিয়াল",
        frozenSnacksTab: "ফ্রোজেন স্ন্যাকস",
        diabeticCornerTab: "ডায়াবেটিক কর্নার",

        // Weekday Deals Tabs
        noodlesTab: "নুডলস",
        pastaTab: "পাস্তা",
        fullCreamMilkTab: "পূর্ণ ক্রিম দুধ",
        regularSpiceTab: "নিয়মিত মশলা",
        biscuitsOthersTab: "বিস্কুট ও অন্যান্য",
        flavouredTeaTab: "ফ্লেভার্ড চা",
        teaEtcTab: "চা ইত্যাদি",

        // Empty States
        noProductsCategory: "এই ক্যাটাগরিতে এখনো কোন পণ্য নেই।",
        checkBackSnacks: "শীঘ্রই সুস্বাদু স্ন্যাকস ও মিষ্টির জন্য চেক করুন!",
        productsComing: "পণ্য শীঘ্রই আসছে!",
        noBeverages: "এখনো কোন পানীয় নেই।",
        beveragesComing: "শীঘ্রই আসছে: চা, কফি, জুস এবং আরো!",
        noFrozenFoods: "এখনো কোন ফ্রোজেন ফুড নেই।",
        frozenComing: "শীঘ্রই আসছে: আইসক্রিম, ফ্রোজেন সবজি এবং আরো!",
        noGadgets: "এখনো কোন গ্যাজেট নেই।",
        gadgetsComing: "শীঘ্রই আসছে: মোবাইল আনুষাঙ্গিক, স্মার্ট ডিভাইস এবং আরো!",

        // Vendor Apply Page
        vendorApplyTitle: "বিক্রেতা হোন",
        vendorApplyDesc: "আমাদের মার্কেটপ্লেসে যোগ দিন এবং বিক্রি শুরু করুন",

        // Track Order
        trackOrderTitle: "আপনার অর্ডার ট্র্যাক করুন",
        enterOrderNumber: "অর্ডার নম্বর দিন",
        track: "ট্র্যাক করুন",
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        return localStorage.getItem('preferredLanguage') || 'bn';
    });

    useEffect(() => {
        localStorage.setItem('preferredLanguage', language);
    }, [language]);

    const t = (key) => {
        return translations[language][key] || key;
    };

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'en' ? 'bn' : 'en');
    };

    const getLocalizedField = (obj, field) => {
        if (!obj) return '';
        if (language === 'bn' && obj[`${field}Bn`]) {
            return obj[`${field}Bn`];
        }
        return obj[field] || '';
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage, getLocalizedField }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
