import React, { createContext, useContext, useState, useEffect } from 'react';
import { translateField as _translateField, getLocalizedFlat } from '../lib/translateField';

const translations = {
  bn: {
    deliverTo: 'ডেলিভারি ঠিকানা',
    bangladesh: 'বাংলাদেশ',
    searchPlaceholder: 'পণ্য, ব্র্যান্ড ও ক্যাটাগরি খুঁজুন',
    searchPlaceholderShort: 'পণ্য খুঁজুন...',
    voiceSearch: 'ভয়েস সার্চ',
    search: 'সার্চ',
    all: 'সব',
    helloSignIn: 'হ্যালো, সাইন ইন করুন',
    accountLists: 'অ্যাকাউন্ট ও তালিকা',
    returns: 'রিটার্ন',
    andOrders: 'ও অর্ডার',
    cart: 'কার্ট',
    signIn: 'সাইন ইন',
    newCustomer: 'নতুন গ্রাহক?',
    startHere: 'এখানে শুরু করুন।',
    yourAccount: 'আপনার অ্যাকাউন্ট',
    yourOrders: 'আপনার অর্ডার',
    yourWishList: 'আপনার উইশলিস্ট',
    primeMembership: 'প্রাইম সদস্যপদ',
    yourRecommendations: 'আপনার সুপারিশ',
    subscribeSave: 'সাবস্ক্রাইব ও সাশ্রয়',
    language: 'ভাষা',
    menuAll: 'সব',
    helpSettings: 'সহায়তা ও সেটিংস',
    customerService: 'গ্রাহক সেবা',
    signOut: 'সাইন আউট',
    manageContent: 'কনটেন্ট ও ডিভাইস পরিচালনা',
    wishList: 'উইশলিস্ট',
    allCategories: 'সকল ক্যাটাগরি',
    digitalContent: 'ডিজিটাল কনটেন্ট ও ডিভাইস',
    shopByDepartment: 'বিভাগ অনুযায়ী কেনাকাটা',
    programsFeatures: 'প্রোগ্রাম ও ফিচার',
    backToTop: 'উপরে ফিরুন ↑',
    getToKnowUs: 'আমাদের সম্পর্কে জানুন',
    makeMoneyWithUs: 'আমাদের সাথে আয় করুন',
    paymentProducts: 'পেমেন্ট পণ্য',
    letUsHelpYou: 'আমরা আপনাকে সাহায্য করব',
    english: 'English',
    bangla: 'বাংলা',
    shopByCategory: 'ক্যাটাগরি অনুযায়ী কেনাকাটা',
    todaysDeals: "আজকের অফার",
    limitedTimeOffers: '— সীমিত সময়ের অফার',
    seeAllDeals: 'সব অফার দেখুন →',
    seeAll: 'সব দেখুন →',
    bestSellers: 'বেস্ট সেলার',
    hot: '🔥 জনপ্রিয়',
    upTo: 'পর্যন্ত',
    off: '% ছাড়',
    prime: 'প্রাইম',
    freeDelivery: 'ফ্রি ডেলিভারি',
    discoverMore: 'আরও দেখুন',
    shopFashionForLess: 'কম দামে ফ্যাশন কিনুন',
    tops: 'টপস',
    bottoms: 'বটমস',
    dresses: 'ড্রেস',
    footwear: 'জুতা',
    seeAllFashion: 'সব ফ্যাশন দেখুন →',
    homeKitchenDeals: 'হোম ও কিচেন অফার',
    kitchen: 'রান্নাঘর',
    dining: 'খাবার',
    decor: 'সাজসজ্জা',
    bedding: 'বিছানার চাদর',
    shopHomeKitchen: 'হোম ও কিচেন কিনুন',
    beautyWellness: 'বিউটি ও ওয়েলনেস',
    skincare: 'স্কিনকেয়ার',
    haircare: 'হেয়ারকেয়ার',
    makeup: 'মেকআপ',
    wellness: 'ওয়েলনেস',
    shopBeauty: 'বিউটি কিনুন',
    electronicsTopPicks: 'ইলেকট্রনিক্স — সেরা পছন্দ',
    gamingUniverse: 'গেমিং দুনিয়া',
    fashionFavourites: 'প্রিয় ফ্যাশন',
    homeKitchenEssentials: 'হোম ও কিচেন প্রয়োজনীয় জিনিস',
    beautyPersonalCare: 'বিউটি ও পার্সোনাল কেয়ার',
    sportsOutdoors: 'খেলাধুলা ও আউটডোর',
    recommendedForYou: 'আপনার জন্য সুপারিশকৃত',
    inspiredByBrowsing: 'আপনার ব্রাউজিং থেকে অনুপ্রাণিত',
    backpacks: 'ব্যাকপ্যাক',
    suitcases: 'স্যুটকেস',
    accessories: 'আনুষাঙ্গিক',
    handbags: 'হ্যান্ডব্যাগ',
    travelEssentials: 'প্রিয় ভ্রমণের প্রয়োজনীয় জিনিস',
    sponsored: 'স্পনসরড',
    boughtPastMonth: 'গত মাসে কেনা হয়েছে',
    was: 'ছিল:',
    addToCart: 'কার্টে যোগ করুন',
    inCart: 'কার্টে আছে',
    getIt: 'পান',
    shoppingCart: 'শপিং কার্ট',
    deselectAll: 'সব নির্বাচন বাতিল করুন',
    price: 'মূল্য',
    inStock: 'স্টকে আছে',
    outOfStock: 'স্টক নেই',
    delete: 'মুছুন',
    saveForLater: 'পরে সংরক্ষণ করুন',
    each: 'প্রতিটি',
    subtotal: 'সাবটোটাল',
    item: 'টি পণ্য',
    items: 'টি পণ্য',
    haveCoupon: 'আপনার কাছে কুপন কোড আছে?',
    apply: 'প্রয়োগ করুন',
    qualifiesFreeDelivery: 'আপনার অর্ডার ফ্রি ডেলিভারির যোগ্য।',
    chooseOption: 'এই অপশন বেছে নিন',
    atCheckout: 'চেকআউটে।',
    shipping: 'শিপিং',
    free: 'ফ্রি',
    orderTotal: 'অর্ডার মোট',
    proceedToCheckout: 'চেকআউটে যান',
    secureCheckout: 'নিরাপদ চেকআউট • SSL এনক্রিপ্টেড',
    youSave: 'আপনি সাশ্রয় করেছেন:',
    withDiscount: 'ছাড়সহ',
    continueShopping: 'কেনাকাটা চালিয়ে যান',
    cartEmpty: 'আপনার ShopZone কার্ট খালি',
    noItemsInCart: 'আপনার শপিং কার্টে কোনো পণ্য নেই।',
    alreadyCustomer: 'ইতিমধ্যে গ্রাহক?',
    toSeeYourCart: 'আপনার কার্ট দেখতে।',
    couponSave10: '১০% ছাড়ের কুপন',
    couponApplied: 'কুপন প্রয়োগ হয়েছে! আপনার অর্ডারে ১০% ছাড়।',
    invalidCoupon: 'ভুল কুপন কোড',
    itemRemoved: 'পণ্য কার্ট থেকে সরানো হয়েছে',
    cartCleared: 'কার্ট খালি করা হয়েছে',
    checkoutDemo: 'চেকআউট একটি ডেমো — কোনো পেমেন্ট প্রসেস হয়নি।',
    signin: 'সাইন ইন',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    yourName: 'আপনার নাম',
    firstLastName: 'প্রথম ও শেষ নাম',
    email: 'ইমেইল',
    password: 'পাসওয়ার্ড',
    forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    atLeast6Chars: 'পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।',
    continueBtn: 'চালিয়ে যান',
    createSholokAccount: 'আপনার Sholok অ্যাকাউন্ট তৈরি করুন',
    pleaseWait: 'অনুগ্রহ করে অপেক্ষা করুন…',
    byContinuing: 'চালিয়ে যাওয়ার মাধ্যমে, আপনি Sholok-এর',
    conditionsOfUse: 'ব্যবহারের শর্তাবলী',
    and: 'এবং',
    privacyNotice: 'গোপনীয়তা নীতি',
    or: 'অথবা',
    dontHaveAccount: 'অ্যাকাউন্ট নেই?',
    alreadyHaveAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    signInInstead: 'পরিবর্তে সাইন ইন করুন',
    help: 'সহায়তা',
    fillAllFields: 'অনুগ্রহ করে সব ফিল্ড পূরণ করুন',
    signedInDemo: 'সফলভাবে সাইন ইন হয়েছে (ডেমো)',
    accountCreatedDemo: 'অ্যাকাউন্ট তৈরি হয়েছে (ডেমো)',
    productNotFound: 'পণ্য পাওয়া যায়নি',
    backToHome: 'হোমে ফিরে যান',
    home: 'হোম',
    brand: 'ব্র্যান্ড',
    ratings: 'রেটিং',
    answeredQuestions: 'উত্তরিত প্রশ্ন',
    boughtInPastMonth: 'গত মাসে কেনা হয়েছে',
    listPrice: 'তালিকা মূল্য',
    includesTaxes: 'প্রযোজ্য কর অন্তর্ভুক্ত।',
    details: 'বিস্তারিত',
    applyCouponLabel: 'প্রয়োগ করুন',
    couponTerms: 'শর্তাবলী',
    aboutThisItem: 'এই পণ্য সম্পর্কে',
    technicalSpecs: 'প্রযুক্তিগত স্পেসিফিকেশন',
    onlyLeftInStock: 'মাত্র টি স্টকে আছে!',
    currentlyUnavailable: 'বর্তমানে অনুপলব্ধ',
    quantity: 'পরিমাণ',
    addedToCart: 'কার্টে যোগ হয়েছে ✓',
    buyNow: 'এখনই কিনুন',
    secureTransaction: 'নিরাপদ লেনদেন',
    shipsFrom: 'পাঠানো হয়',
    freeReturns: 'ফ্রি রিটার্ন',
    within30Days: 'দিনের মধ্যে',
    addGiftOption: 'গিফট অপশন যোগ করুন',
    customerReviews: 'গ্রাহক পর্যালোচনা',
    outOf5: '৫ এর মধ্যে',
    globalRatings: 'মোট রেটিং',
    star: 'তারা',
    up: 'এর বেশি',
    verifiedPurchase: 'যাচাইকৃত ক্রয়',
    helpful: 'সহায়ক?',
    yes: 'হ্যাঁ',
    no: 'না',
    moreFrom: 'আরও থেকে',
    addedToCartToast: 'কার্টে যোগ করা হয়েছে',
    resultsFor: 'ফলাফল',
    allProducts: 'সব পণ্য',
    results: 'টি ফলাফল',
    sortBy: 'সাজান:',
    featured: 'বৈশিষ্ট্যযুক্ত',
    priceLowHigh: 'মূল্য: কম থেকে বেশি',
    priceHighLow: 'মূল্য: বেশি থেকে কম',
    avgCustomerReview: 'গড় গ্রাহক রিভিউ',
    newestArrivals: 'নতুন সংযোজন',
    filterResults: 'ফলাফল ফিল্টার করুন',
    category: 'ক্যাটাগরি',
    clearAllFilters: 'সব ফিল্টার মুছুন',
    primeEligible: 'প্রাইম যোগ্য',
    noResultsFound: 'কোনো ফলাফল পাওয়া যায়নি',
    tryDifferentKeywords: 'ভিন্ন কীওয়ার্ড চেষ্টা করুন বা কিছু ফিল্টার সরান',
    clearFilters: 'ফিল্টার মুছুন',
    filterSort: 'ফিল্টার ও সাজান',
    showResults: 'ফলাফল দেখান',
  },
  en: {
    deliverTo: 'Deliver to',
    bangladesh: 'Bangladesh',
    searchPlaceholder: 'Search products, brands and categories',
    searchPlaceholderShort: 'Search products...',
    voiceSearch: 'Voice search',
    search: 'Search',
    all: 'All',
    helloSignIn: 'Hello, sign in',
    accountLists: 'Account & Lists',
    returns: 'Returns',
    andOrders: '& Orders',
    cart: 'Cart',
    signIn: 'Sign in',
    newCustomer: 'New customer?',
    startHere: 'Start here.',
    yourAccount: 'Your Account',
    yourOrders: 'Your Orders',
    yourWishList: 'Your Wish List',
    primeMembership: 'Prime Membership',
    yourRecommendations: 'Your Recommendations',
    subscribeSave: 'Subscribe & Save',
    language: 'Language',
    menuAll: 'All',
    helpSettings: 'Help & Settings',
    customerService: 'Customer Service',
    signOut: 'Sign Out',
    manageContent: 'Manage Content & Devices',
    wishList: 'Wish List',
    allCategories: 'All Categories',
    digitalContent: 'Digital Content & Devices',
    shopByDepartment: 'Shop by Department',
    programsFeatures: 'Programs & Features',
    backToTop: 'Back to top ↑',
    getToKnowUs: 'Get to Know Us',
    makeMoneyWithUs: 'Make Money with Us',
    paymentProducts: 'Payment Products',
    letUsHelpYou: 'Let Us Help You',
    english: 'English',
    bangla: 'বাংলা',
    shopByCategory: 'Shop by Category',
    todaysDeals: "Today's Deals",
    limitedTimeOffers: '— Limited time offers',
    seeAllDeals: 'See all deals →',
    seeAll: 'See all →',
    bestSellers: 'Best Sellers',
    hot: '🔥 Hot',
    upTo: 'Up to',
    off: '% off',
    prime: 'Prime',
    freeDelivery: 'FREE delivery',
    discoverMore: 'Discover more',
    shopFashionForLess: 'Shop Fashion for less',
    tops: 'Tops & Tees',
    bottoms: 'Bottoms',
    dresses: 'Dresses',
    footwear: 'Footwear',
    seeAllFashion: 'See all fashion →',
    homeKitchenDeals: 'Home & Kitchen Deals',
    kitchen: 'Kitchen',
    dining: 'Dining',
    decor: 'Décor',
    bedding: 'Bedding',
    shopHomeKitchen: 'Shop Home & Kitchen',
    beautyWellness: 'Beauty & Wellness',
    skincare: 'Skincare',
    haircare: 'Haircare',
    makeup: 'Makeup',
    wellness: 'Wellness',
    shopBeauty: 'Shop Beauty',
    electronicsTopPicks: 'Electronics — Top Picks',
    gamingUniverse: 'Gaming Universe',
    fashionFavourites: 'Fashion Favourites',
    homeKitchenEssentials: 'Home & Kitchen Essentials',
    beautyPersonalCare: 'Beauty & Personal Care',
    sportsOutdoors: 'Sports & Outdoors',
    recommendedForYou: 'Recommended For You',
    inspiredByBrowsing: 'Inspired by Your Browsing',
    backpacks: 'Backpacks',
    suitcases: 'Suitcases',
    accessories: 'Accessories',
    handbags: 'Handbags',
    travelEssentials: 'Most-loved travel essentials',
    sponsored: 'Sponsored',
    boughtPastMonth: 'bought past month',
    was: 'Was:',
    addToCart: 'Add to Cart',
    inCart: 'In Cart',
    getIt: 'Get it',
    shoppingCart: 'Shopping Cart',
    deselectAll: 'Deselect all items',
    price: 'Price',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    delete: 'Delete',
    saveForLater: 'Save for later',
    each: 'each',
    subtotal: 'Subtotal',
    item: 'item',
    items: 'items',
    haveCoupon: 'Have a coupon code?',
    apply: 'Apply',
    qualifiesFreeDelivery: 'Your order qualifies for FREE Delivery.',
    chooseOption: 'Choose this option',
    atCheckout: 'at checkout.',
    shipping: 'Shipping',
    free: 'FREE',
    orderTotal: 'Order Total',
    proceedToCheckout: 'Proceed to Checkout',
    secureCheckout: 'Secure checkout • SSL encrypted',
    youSave: 'You Save:',
    withDiscount: 'with discount',
    continueShopping: 'Continue Shopping',
    cartEmpty: 'Your ShopZone Cart is empty',
    noItemsInCart: 'You have no items in your shopping cart.',
    alreadyCustomer: 'Already a customer?',
    toSeeYourCart: 'to see your cart.',
    couponSave10: '10% off your order',
    couponApplied: 'Coupon applied! 10% off your order.',
    invalidCoupon: 'Invalid coupon code',
    itemRemoved: 'Item removed from cart',
    cartCleared: 'Cart cleared',
    checkoutDemo: 'Checkout is a demo — no payment processed.',
    signin: 'Sign in',
    createAccount: 'Create account',
    yourName: 'Your name',
    firstLastName: 'First and last name',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    atLeast6Chars: 'Passwords must be at least 6 characters.',
    continueBtn: 'Continue',
    createSholokAccount: 'Create your Sholok account',
    pleaseWait: 'Please wait…',
    byContinuing: "By continuing, you agree to Sholok's",
    conditionsOfUse: 'Conditions of Use',
    and: 'and',
    privacyNotice: 'Privacy Notice',
    or: 'Or',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    signInInstead: 'Sign in instead',
    help: 'Help',
    fillAllFields: 'Please fill in all fields',
    signedInDemo: 'Signed in successfully (demo)',
    accountCreatedDemo: 'Account created (demo)',
    productNotFound: 'Product not found',
    backToHome: 'Back to Home',
    home: 'Home',
    brand: 'Brand',
    ratings: 'ratings',
    answeredQuestions: 'answered questions',
    boughtInPastMonth: 'bought in past month',
    listPrice: 'List price',
    includesTaxes: 'Includes applicable taxes.',
    details: 'Details',
    applyCouponLabel: 'Apply',
    couponTerms: 'Terms',
    aboutThisItem: 'About this item',
    technicalSpecs: 'Technical Specifications',
    onlyLeftInStock: 'Only left in stock!',
    currentlyUnavailable: 'Currently unavailable',
    quantity: 'Quantity:',
    addedToCart: 'Added to Cart ✓',
    buyNow: 'Buy Now',
    secureTransaction: 'Secure transaction',
    shipsFrom: 'Ships from',
    freeReturns: 'Free returns',
    within30Days: 'within 30 days',
    addGiftOption: 'Add gift option',
    customerReviews: 'Customer Reviews',
    outOf5: 'out of 5',
    globalRatings: 'global ratings',
    star: 'star',
    up: '& Up',
    verifiedPurchase: 'Verified Purchase',
    helpful: 'Helpful?',
    yes: 'Yes',
    no: 'No',
    moreFrom: 'More from',
    addedToCartToast: 'added to cart',
    resultsFor: 'Results for',
    allProducts: 'All Products',
    results: 'results',
    sortBy: 'Sort by:',
    featured: 'Featured',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    avgCustomerReview: 'Avg. Customer Review',
    newestArrivals: 'Newest Arrivals',
    filterResults: 'Filter Results',
    category: 'Category',
    clearAllFilters: 'Clear all filters',
    primeEligible: 'Prime eligible',
    noResultsFound: 'No results found',
    tryDifferentKeywords: 'Try different keywords or remove some filters',
    clearFilters: 'Clear Filters',
    filterSort: 'Filter & Sort',
    showResults: 'Show Results',
  },
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    if (typeof window === 'undefined') return 'bn';
    return localStorage.getItem('preferredLanguage') || 'bn';
  });

  useEffect(() => {
    localStorage.setItem('preferredLanguage', language);
  }, [language]);

  const setLanguage = (lang) => setLanguageState(lang);

  const t = (key) => translations[language]?.[key] ?? translations.bn[key] ?? key;

  /**
   * Resolve a multilingual field from a data object.
   * Handles both:
   *  - New nested format:   product.name = { en: 'Laptop', bn: 'ল্যাপটপ' }
   *  - Legacy flat format:  product.title / product.titleBn
   *
   * @param {Object} obj       - data object
   * @param {string} fieldName - base field name (e.g. 'title', 'name')
   * @returns {string}
   */
  const getLocalizedField = (obj, fieldName) => {
    if (!obj) return '';
    const rawField = obj[fieldName];
    // New nested multilingual object: { en, bn }
    if (rawField && typeof rawField === 'object' && ('en' in rawField || 'bn' in rawField)) {
      return _translateField(rawField, language);
    }
    // Legacy flat approach: titleBn / nameBn
    return getLocalizedFlat(obj, fieldName, language);
  };

  /**
   * Direct translateField — resolves any { en, bn } object or plain string.
   */
  const tf = (field, fallback = '') => _translateField(field, language, fallback);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getLocalizedField, translateField: tf }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
