import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

const translations = {
  en: {
    // ── Sidebar ──────────────────────────────────────────────────────────────
    dashboard: 'Dashboard',
    categories: 'Categories',
    products: 'Products',
    customers: 'Customers',
    orders: 'Orders',
    payments: 'Payments',
    shipping: 'Shipping',
    shipments: 'Shipments',
    vendors: 'Vendors',
    warehouses: 'Warehouses',
    couriers: 'Couriers',
    deliveryCoverage: 'Delivery Coverage',
    grocerySettings: 'Grocery Settings',
    codSettlement: 'COD & Settlement',
    brands: 'Brands',
    returns: 'Returns',
    reports: 'Reports',
    marketing: 'Marketing',
    campaigns: 'Campaigns',
    reviews: 'Reviews',
    searchAnalytics: 'Search Analytics',
    liveSessions: 'Live Sessions',
    vendorReviews: 'Vendor Reviews',
    settings: 'Settings',
    homePageProduct: 'Home Page Product',
    logout: 'Logout',
    switchLanguage: 'বাংলা',
    // ── Common actions ───────────────────────────────────────────────────────
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    addNew: 'Add New',
    search: 'Search',
    filter: 'Filter',
    filters: 'Filters',
    clearAll: 'Clear all',
    clear: 'Clear',
    status: 'Status',
    actions: 'Actions',
    name: 'Name',
    nameBnLabel: 'Name (Bangla)',
    description: 'Description',
    price: 'Price',
    stock: 'Stock',
    category: 'Category',
    brand: 'Brand',
    sku: 'SKU',
    loading: 'Loading...',
    noData: 'No data found',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    total: 'Total',
    active: 'Active',
    inactive: 'Inactive',
    draft: 'Draft',
    published: 'Published',
    all: 'All',
    none: 'None',
    select: 'Select',
    upload: 'Upload',
    remove: 'Remove',
    view: 'View',
    close: 'Close',
    update: 'Update',
    create: 'Create',
    refresh: 'Refresh',
    export: 'Export CSV',
    exporting: 'Exporting…',
    import: 'Import',
    selected: 'selected',
    previous: 'Previous',
    next: 'Next',
    prev: 'Prev',
    saving: 'Saving…',
    // ── Dashboard ────────────────────────────────────────────────────────────
    welcomeBack: "Welcome back! Here's your store overview.",
    totalRevenue: 'Total Revenue',
    revenueOverview: 'Revenue Overview',
    salesByCategory: 'Sales by Category',
    ordersTrend: 'Orders Trend',
    recentOrders: 'Recent Orders',
    loadingOrders: 'Loading orders...',
    noOrdersYet: 'No orders yet',
    vsLastMonth: 'vs last month',
    inventoryValue: 'Inventory Value',
    totalOrders: 'Total Orders',
    totalCustomers: 'Total Customers',
    totalProducts: 'Total Products',
    // ── Products ─────────────────────────────────────────────────────────────
    manageProductCatalog: 'Manage your product catalog',
    addProduct: 'Add Product',
    lowStock: 'Low Stock',
    searchByNameOrSku: 'Search by name or SKU...',
    statusVisibility: 'Status / Visibility',
    allStatus: 'All Status',
    outOfStock: 'Out of Stock',
    archived: 'Archived',
    allCategories: 'All Categories',
    stockStatus: 'Stock Status',
    allStock: 'All Stock',
    inStock: 'In Stock',
    priceRange: 'Price Range (৳)',
    dateFrom: 'Date Added — From',
    dateTo: 'Date Added — To',
    updateStock: 'Update Stock',
    noProductsFound: 'No products found',
    uncategorized: 'Uncategorized',
    archiveProduct: 'Archive',
    publishProduct: 'Publish',
    newBadge: 'New',
    // ── Product form ─────────────────────────────────────────────────────────
    addProductTitle: 'Add New Product',
    editProduct: 'Edit Product',
    productNameEn: 'Product Name (English) *',
    productNameBn: 'Product Name (Bangla)',
    urlSlug: 'URL Slug *',
    descriptionEn: 'Description (English)',
    descriptionBn: 'Description (Bangla)',
    shortDescEn: 'Short Description (English)',
    shortDescBn: 'Short Description (Bangla)',
    regularPrice: 'Regular Price *',
    salePrice: 'Sale Price',
    tags: 'Tags',
    addTag: 'Add Tag',
    images: 'Images',
    metaTitleEn: 'Meta Title (English)',
    metaDescriptionEn: 'Meta Description (English)',
    saveProduct: 'Save Product',
    general: 'General',
    pricingStock: 'Pricing & Stock',
    variants: 'Variants',
    publish: 'Publish',
    related: 'Related',
    seo: 'SEO',
    addVariant: 'Add Variant',
    variantName: 'Variant Name',
    variantSku: 'Variant SKU',
    variantPrice: 'Variant Price',
    variantSalePrice: 'Variant Sale Price',
    variantStock: 'Variant Stock',
    barcode: 'Barcode',
    weight: 'Weight (kg)',
    lowStockThreshold: 'Low Stock Threshold',
    featured: 'Featured',
    isNew: 'New Arrival',
    onSale: 'On Sale',
    visibility: 'Visibility',
    visible: 'Visible',
    hidden: 'Hidden',
    shippingClass: 'Shipping Class',
    shippingCharge: 'Shipping Charge',
    relatedProducts: 'Related Products',
    upsellProducts: 'Upsell Products',
    crossSellProducts: 'Cross-Sell Products',
    // ── Categories ───────────────────────────────────────────────────────────
    manageCategoriesDesc: 'Manage product categories — tree view',
    addCategory: 'Add Category',
    trash: 'Trash',
    searchCategories: 'Search categories (English or বাংলা)…',
    collapseAll: 'Collapse All',
    expandAll: 'Expand All',
    activate: 'Activate',
    deactivate: 'Deactivate',
    trashIsEmpty: 'Trash is empty',
    noCategoriesYet: 'No categories yet. Add your first category!',
    moveToTrash: 'Move to Trash',
    permanentlyDelete: 'Permanently Delete?',
    restore: 'Restore',
    deleteForever: 'Delete Forever',
    addSubcategory: 'Add subcategory',
    parentCategory: 'Parent Category',
    categoryName: 'Category Name (English)',
    categoryNameBn: 'Category Name (Bangla)',
    categorySlug: 'Category Slug',
    editCategory: 'Edit Category',
    // ── Orders ───────────────────────────────────────────────────────────────
    manageTrackOrders: 'Manage and track all customer orders',
    pendingOrders: 'Pending Orders',
    paidOrders: 'Paid Orders',
    searchOrderOrCustomer: 'Search order # or customer…',
    allPayments: 'All Payments',
    setStatus: 'Set Status',
    setPayment: 'Set Payment',
    orderNumber: 'Order #',
    items: 'Items',
    tracking: 'Tracking',
    date: 'Date',
    noOrdersFound: 'No orders found',
    orderDetails: 'Order Details',
    orderStatus: 'Order Status',
    paymentStatus: 'Payment Status',
    orderDate: 'Order Date',
    paymentMethod: 'Payment Method',
    shippingTracking: 'Shipping / Tracking',
    shippingAddress: 'Shipping Address',
    orderItems: 'Order Items',
    qty: 'Qty',
    subtotal: 'Subtotal',
    tax: 'Tax',
    discount: 'Discount',
    adminNotes: 'Admin Notes',
    noNotes: 'No notes',
    orderTimeline: 'Order Timeline',
    viewInvoice: 'View Invoice',
    courierName: 'Courier Name',
    trackingNumber: 'Tracking Number',
    estDelivery: 'Estimated Delivery Date',
    saveTracking: 'Save Tracking',
    internalNote: 'Add an internal note…',
    saveNote: 'Save Note',
    printInvoice: 'Print Invoice',
    invoice: 'Invoice',
    setTracking: 'Set Tracking',
    addNote: 'Add Note',
    markProcessing: 'Mark Processing',
    markDelivered: 'Mark Delivered',
    confirmed: 'Confirmed',
    processing: 'Processing',
    shipped: 'Shipped',
    outForDelivery: 'Out for Delivery',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    refunded: 'Refunded',
    paid: 'Paid',
    failed: 'Failed',
    pending: 'Pending',
    // ── Customers ────────────────────────────────────────────────────────────
    manageCustomerDb: 'Manage your customer database',
    addCustomer: 'Add Customer',
    returning: 'Returning',
    avgLtv: 'Avg LTV',
    perCustomer: 'per customer',
    avgFrequency: 'Avg Frequency',
    ordersPerCustomer: 'orders / customer',
    activeRecent: 'Active (90d)',
    loggedInRecently: 'logged in recently',
    activeCustomers: 'Active Customers',
    searchCustomers: 'Search customers...',
    blocked: 'Blocked',
    allGroups: 'All Groups',
    regular: 'Regular',
    wholesale: 'Wholesale',
    vip: 'VIP',
    dealer: 'Dealer',
    customersSelected: 'customer(s) selected',
    sendMessage: 'Send Message',
    contact: 'Contact',
    group: 'Group',
    spent: 'Spent',
    points: 'Points',
    loadingCustomers: 'Loading customers...',
    noCustomersFound: 'No customers found',
    suspendedUntil: 'Suspended until',
    changeGroup: 'Change Group',
    managePoints: 'Manage Points',
    suspendUntil: 'Suspend Until...',
    editCustomer: 'Edit Customer',
    addNewCustomer: 'Add New Customer',
    deleteCustomer: 'Delete Customer',
    customerDetails: 'Customer Details',
    profile: 'Profile',
    security: 'Security',
    messages: 'Messages',
    rewardPoints: 'Reward Points',
    totalSpent: 'Total Spent',
    lastLogin: 'Last Login',
    totalEarned: 'Total Earned',
    totalRedeemed: 'Total Redeemed',
    available: 'Available',
    noPointsHistory: 'No points history',
    wishlistEmpty: 'Wishlist is empty',
    savedAddressBook: 'Saved address book',
    addAddress: 'Add Address',
    noAddressSaved: 'No addresses saved',
    accountSecurity: 'Account Security',
    loginHistory: 'Login History',
    resetPassword: 'Reset Password',
    activationLink: 'Activation Link',
    generateLink: 'Generate Link',
    noMessagesSent: 'No messages sent yet',
    newMessage: 'New Message',
    importCustomers: 'Import Customers',
    editAddress: 'Edit Address',
    // ── Brands ───────────────────────────────────────────────────────────────
    searchBrands: 'Search brands…',
    bengaliLabel: 'Bengali',
    logoUrl: 'Logo URL',
    bannerUrl: 'Banner URL',
    website: 'Website',
    sortOrder: 'Sort Order',
    noBrandsFound: 'No brands found',
    addBrand: 'Add Brand',
    editBrand: 'Edit Brand',
    brandName: 'Brand Name',
    // ── Vendors ──────────────────────────────────────────────────────────────
    manageMarketplaceVendors: 'Manage marketplace vendors',
    addVendor: 'Add Vendor',
    totalVendors: 'Total Vendors',
    pendingApproval: 'Pending Approval',
    codEnabled: 'COD Enabled',
    searchVendors: 'Search vendors...',
    suspended: 'Suspended',
    location: 'Location',
    cod: 'COD',
    balance: 'Balance',
    approve: 'Approve',
    reject: 'Reject',
    noVendorsFound: 'No vendors found',
    editVendor: 'Edit Vendor',
    vendorName: 'Vendor Name *',
    businessName: 'Business Name',
    district: 'District',
    rejectionReason: 'Rejection reason...',
    rejectVendorTitle: 'Reject Vendor',
    recordDeposit: 'Record Deposit',
    amountBdt: 'Amount (BDT) *',
    // ── Payments ─────────────────────────────────────────────────────────────
    trackManagePayments: 'Track and manage payment transactions',
    totalTransactions: 'Total Transactions',
    completed: 'Completed',
    totalReceived: 'Total Received',
    pendingAmount: 'Pending Amount',
    searchByTransactionId: 'Search by transaction ID...',
    partRefunded: 'Part. Refunded',
    allMethods: 'All Methods',
    cashOnDelivery: 'Cash on Delivery',
    bankTransfer: 'Bank Transfer',
    transactionId: 'Transaction ID',
    paidAt: 'Paid At',
    loadingPayments: 'Loading payments...',
    noPaymentsFound: 'No payments found',
    markCompleted: 'Mark Completed',
    verifyPayment: 'Verify Payment',
    markFailed: 'Mark Failed',
    issueRefund: 'Issue Refund',
    paymentDetails: 'Payment Details',
    processRefund: 'Process Refund',
    originalAmount: 'Original Amount',
    refundType: 'Refund Type',
    fullRefund: 'Full Refund',
    partialRefund: 'Partial Refund',
    refundAmount: 'Refund Amount (৳)',
    reason: 'Reason',
    // ── Shipping ─────────────────────────────────────────────────────────────
    shippingMgmt: 'Shipping Management',
    manageDeliveryAreas: 'Manage delivery areas and track shipments',
    pendingShipment: 'Pending Shipment',
    shippedInTransit: 'Shipped / In Transit',
    activeAreas: 'Active Areas',
    shipmentOrders: 'Shipment Orders',
    deliveryAreas: 'Delivery Areas',
    shippingMethods: 'Shipping Methods',
    searchOrders: 'Search orders...',
    noShipmentOrders: 'No shipment orders found',
    addArea: 'Add Area',
    city: 'City',
    freeAbove: 'Free Above',
    estDays: 'Est. Days',
    days: 'day(s)',
    noDeliveryAreasFound: 'No delivery areas found',
    editDeliveryArea: 'Edit Delivery Area',
    addDeliveryArea: 'Add Delivery Area',
    areaName: 'Area Name',
    deliveryCharge: 'Delivery Charge (৳)',
    freeDeliveryAbove: 'Free Delivery Above',
    estimatedDeliveryDays: 'Estimated Delivery Days',
    postalCodes: 'Postal Codes (comma separated)',
    updateArea: 'Update Area',
    createArea: 'Create Area',
    addMethod: 'Add Method',
    baseCharge: 'Base Charge',
    noShippingMethods: 'No shipping methods configured',
    editShippingMethod: 'Edit Shipping Method',
    addShippingMethod: 'Add Shipping Method',
    flatRate: 'Flat Rate',
    weightBased: 'Weight Based',
    freeShipping: 'Free Shipping',
    express: 'Express',
    freeThreshold: 'Free Threshold (৳)',
    updateMethod: 'Update Method',
    createMethod: 'Create Method',
    // ── Shipments ────────────────────────────────────────────────────────────
    trackManageShipments: 'Track and manage all shipments',
    inTransit: 'In Transit',
    searchShipment: 'Search shipment number, order ID, tracking...',
    readyForPickup: 'Ready for Pickup',
    pickedUp: 'Picked Up',
    failedDelivery: 'Failed Delivery',
    returnedStatus: 'Returned',
    shipmentNo: 'Shipment #',
    source: 'Source',
    courier: 'Courier',
    noShipmentsFound: 'No shipments found',
    pageOf: 'Page {n} of {m}',
    shipmentDetails: 'Shipment Details',
    deliveryChargeLbl: 'Delivery Charge',
    eta: 'ETA',
    trackingHistory: 'Tracking History',
    updateShipment: 'Update Shipment',
    selectCourier: 'Select courier...',
    noteDescription: 'Note / Description',
    // ── Returns ──────────────────────────────────────────────────────────────
    returnRequests: 'Return Requests',
    allTypes: 'All Types',
    returnType: 'Return',
    exchangeType: 'Exchange',
    returnNo: 'Return #',
    refundAmt: 'Refund Amt',
    noReturnRequests: 'No return requests',
    returnRequest: 'Return Request',
    adminNote: 'Admin Note',
    updateStatus: 'Update Status',
    internalNoteMsg: 'Internal note or customer message…',
    // ── Reports ──────────────────────────────────────────────────────────────
    reportsAnalytics: 'Reports & Analytics',
    businessInsights: 'Business insights and performance metrics',
    days7: '7 Days',
    days30: '30 Days',
    days90: '90 Days',
    year1: '1 Year',
    overview: 'overview',
    sales: 'sales',
    finance: 'finance',
    stockTab: 'stock',
    todaysRevenue: "Today's Revenue",
    todaysOrders: "Today's Orders",
    monthlyRevenue: 'Monthly Revenue',
    revenueTrend: 'Revenue Trend',
    salesSummary: 'Sales Summary',
    avgOrderValue: 'Avg Order Value',
    salesByPaymentMethod: 'Sales by Payment Method',
    noDataLabel: 'No data',
    ordersByStatus: 'Orders by Status',
    orderMetrics: 'Order Metrics',
    cancelledOrders: 'Cancelled Orders',
    refundedOrders: 'Refunded Orders',
    newLast30Days: 'New (Last 30 Days)',
    topSpenders: 'Top Spenders',
    topCustomersBySpending: 'Top Customers by Spending',
    topSellingProducts: 'Top Selling Products',
    qtySold: 'Qty Sold',
    lowStockProducts: 'Low Stock Products',
    noSalesData: 'No sales data',
    noLowStockProducts: 'No low stock products',
    loadingFinanceData: 'Loading finance data...',
    noFinanceData: 'No finance data available.',
    netRevenue: 'Net Revenue',
    shippingRevenue: 'Shipping Revenue',
    discounts: 'Discounts',
    refunds: 'Refunds',
    pendingPayments: 'Pending Payments',
    revenueByPaymentMethod: 'Revenue by Payment Method',
    transactions: 'Transactions',
    stockValue: 'Stock Value',
    lowStockItems: 'Low Stock Items',
    allProductsWellStocked: 'All products well-stocked',
    failedToExport: 'Failed to export',
    // ── Marketing ────────────────────────────────────────────────────────────
    marketingPromotion: 'Marketing & Promotion',
    manageCouponsDesc: 'Manage coupons, banners and promotional campaigns',
    activeCoupons: 'Active Coupons',
    totalRedemptions: 'Total Redemptions',
    activeBanners: 'Active Banners',
    totalCoupons: 'Total Coupons',
    coupons: 'Coupons',
    banners: 'Banners',
    flashSales: 'Flash Sales',
    emailCampaigns: 'Email Campaigns',
    addCoupon: 'Add Coupon',
    code: 'Code',
    value: 'Value',
    minPurchase: 'Min Purchase',
    used: 'Used',
    expires: 'Expires',
    expired: 'Expired',
    noCouponsYet: 'No coupons yet',
    addBanner: 'Add Banner',
    image: 'Image',
    title: 'Title',
    placement: 'Placement',
    priority: 'Priority',
    noBannersYet: 'No banners yet',
    editCoupon: 'Edit Coupon',
    createCoupon: 'Create Coupon',
    couponCode: 'Coupon Code',
    discountType: 'Discount Type',
    discountValue: 'Discount Value',
    minPurchaseLbl: 'Min Purchase (৳)',
    maxDiscount: 'Max Discount (৳)',
    startDate: 'Start Date',
    endDate: 'End Date',
    usageLimit: 'Usage Limit (0 = unlimited)',
    perCustomerLimit: 'Per Customer Limit',
    percentage: 'Percentage',
    fixedAmount: 'Fixed Amount',
    freeDelivery: 'Free Delivery',
    updateCoupon: 'Update Coupon',
    addFlashSale: 'Add Flash Sale',
    badge: 'Badge',
    start: 'Start',
    end: 'End',
    ended: 'Ended',
    noFlashSalesYet: 'No flash sales yet',
    editFlashSale: 'Edit Flash Sale',
    createFlashSale: 'Create Flash Sale',
    badgeLabel: 'Badge Label (optional)',
    newCampaign: 'New Campaign',
    subject: 'Subject',
    audience: 'Audience',
    sentLabel: 'Sent',
    noCampaignsYet: 'No campaigns yet',
    editCampaign: 'Edit Campaign',
    createCampaign: 'Create Campaign',
    allCustomersAudience: 'All Customers',
    newCustomersAudience: 'New Customers',
    inactiveAudience: 'Inactive',
    scheduled: 'Scheduled',
    scheduledAt: 'Scheduled At',
    updateCampaign: 'Update Campaign',
    manageProducts: 'Manage Products',
    searchProductsByName: 'Search products by name...',
    productSelected: 'product(s) selected',
    saveProducts: 'Save Products',
    editBanner: 'Edit Banner',
    createBanner: 'Create Banner',
    imageUrl: 'Image URL',
    linkUrl: 'Link URL',
    homepageTop: 'Homepage Top',
    homepageSlider: 'Homepage Slider',
    sidebar: 'Sidebar',
    popup: 'Popup',
    updateBanner: 'Update Banner',
    deleteFlashSale: 'Delete this flash sale?',
    deleteCampaign: 'Delete this campaign?',
    deleteCoupon: 'Delete this coupon?',
    // ── Reviews ──────────────────────────────────────────────────────────────
    reviewsRatings: 'Reviews & Ratings',
    manageReviewsDesc: 'Manage product reviews from customers',
    totalReviews: 'Total Reviews',
    approved: 'Approved',
    avgRating: 'Avg Rating',
    searchReviews: 'Search by customer, product, or comment...',
    filterByStatus: 'Filter by status',
    noReviewsFound: 'No reviews found',
    selectAll: 'Select All',
    unknownProduct: 'Unknown Product',
    unknown: 'Unknown',
    deleteReviewConfirm: 'Are you sure you want to delete this review?',
    selectReviewsFirst: 'Select reviews first',
    rejected: 'Rejected',
    // ── VendorReviews ────────────────────────────────────────────────────────
    noVendorReviewsFound: 'No vendor reviews found',
    reviewedBy: 'reviewed by',
    // ── SearchAnalytics ──────────────────────────────────────────────────────
    popularSearches: 'Popular Searches (All Time)',
    noSearchDataYet: 'No search data yet',
    trendingNow: 'Trending Now (24h)',
    noTrendingSearches: 'No trending searches in last 24 hours',
    // ── LiveSessions ─────────────────────────────────────────────────────────
    liveShoppingSessions: 'Live Shopping Sessions',
    noLiveSessionsYet: 'No live sessions yet',
    vendorsCanCreateSessions: 'Vendors can create sessions from their panel',
    store: 'Store',
    viewers: 'Viewers',
    liveStatus: 'live',
    scheduledStatus: 'scheduled',
    endedStatus: 'ended',
    // ── Couriers ─────────────────────────────────────────────────────────────
    manageCouriersDesc: 'Manage third-party delivery partners',
    addCourier: 'Add Courier',
    trackingUrlTemplate: 'Tracking URL Template',
    noCouriersFound: 'No couriers found',
    editCourier: 'Edit Courier',
    courierCode: 'Code (e.g. redx, pathao)',
    trackingUrlHint: 'Tracking URL Template (use {tracking} as placeholder)',
    // ── Warehouses ───────────────────────────────────────────────────────────
    manageWarehousesDesc: 'Manage warehouse locations',
    addWarehouse: 'Add Warehouse',
    noWarehouses: 'No warehouses',
    editWarehouse: 'Edit Warehouse',
    defaultLbl: 'Default',
    division: 'Division',
    contactName: 'Contact Name',
    contactPhone: 'Contact Phone',
    setAsDefaultWarehouse: 'Set as Default Warehouse',
    // ── DeliveryCoverage ─────────────────────────────────────────────────────
    manageGroceryDelivery: 'Manage grocery delivery areas and nationwide shipping policies',
    groceryCoverage: 'Grocery Coverage',
    shippingPolicies: 'Shipping Policies',
    groceryDeliveryLimited: 'Grocery delivery is limited to Dhaka city areas only. Enable/disable individual areas.',
    noAreasAdded: 'No areas added',
    weightBasedShipping: 'Weight-based shipping charges for nationwide delivery.',
    addPolicy: 'Add Policy',
    areaZone: 'Area / Zone',
    extraPerKg: 'Extra / kg',
    insideCity: 'Inside City',
    nationwide: 'Nationwide',
    noPoliciesFound: 'No policies found',
    editArea: 'Edit Area',
    addDeliveryAreaTitle: 'Add Delivery Area',
    areaNameEnglish: 'Area Name (English) *',
    areaNameBengali: 'Area Name (Bengali)',
    editShippingPolicy: 'Edit Shipping Policy',
    addShippingPolicy: 'Add Shipping Policy',
    zoneAreaName: 'Zone / Area Name',
    insideCityFaster: 'Inside City (faster delivery)',
    baseWeight: 'Base Weight (kg)',
    baseChargeLbl: 'Base Charge (৳)',
    extraPerKgLbl: 'Extra per kg (৳)',
    freeThresholdLbl: 'Free Threshold (৳)',
    etaMin: 'ETA Min (days)',
    etaMax: 'ETA Max (days)',
    optional: 'Optional',
    // ── GrocerySettings ──────────────────────────────────────────────────────
    configureDelivery: 'Configure delivery time slots and grocery delivery settings',
    deliveryTimeSlots: 'Delivery Time Slots',
    addSlot: 'Add Slot',
    label: 'Label',
    timeWindow: 'Time Window',
    maxOrders: 'Max Orders',
    unlimited: 'Unlimited',
    noSlotsConfigured: 'No slots configured',
    generalSettings: 'General Settings',
    minPrepTime: 'Minimum Preparation Time (hours)',
    deliveryDaysAvailable: 'Delivery Days Available (1 = Today only, 2 = Today + Tomorrow)',
    groceryDeliveryEnabled: 'Grocery Delivery Enabled (1 = yes, 0 = no)',
    freeDeliveryMinOrder: 'Free Delivery Min Order Amount (৳)',
    insideCityCharge: 'Inside City Delivery Charge (৳)',
    outsideCityCharge: 'Outside City Delivery Charge (৳)',
    saveSettings: 'Save Settings',
    editSlot: 'Edit Slot',
    addTimeSlot: 'Add Time Slot',
    startTime: 'Start Time *',
    endTime: 'End Time *',
    maxOrdersBlank: 'Max Orders (leave blank for unlimited)',
    // ── CodSettlement ────────────────────────────────────────────────────────
    manageCodCollections: 'Manage cash-on-delivery collections and vendor settlements',
    allVendors: 'All Vendors',
    newSettlement: 'New Settlement',
    pendingCodCollection: 'Pending COD Collection',
    pendingSettlements: 'Pending Settlements',
    codTransactions: 'COD Transactions',
    settlementRecords: 'Settlement Records',
    collectedAt: 'Collected At',
    markCollected: 'Mark Collected',
    noCodTransactions: 'No COD transactions',
    period: 'Period',
    platformFee: 'Platform Fee',
    netPayout: 'Net Payout',
    processSettle: 'Process',
    noSettlementRecords: 'No settlement records',
    newSettlementRecord: 'New Settlement Record',
    periodStart: 'Period Start *',
    periodEnd: 'Period End *',
    codAmountLbl: 'COD Amount (৳)',
    platformFeeLbl: 'Platform Fee (৳)',
    createSettlement: 'Create Settlement',
    processSettlementTitle: 'Process Settlement',
    deductedFromWallet: "This amount will be deducted from the vendor's wallet.",
    paymentMethodLbl: 'Payment Method',
    paymentReference: 'Payment Reference',
    paymentReferenceHint: 'Transaction ID',
    confirmProcess: 'Confirm & Process',
    // ── Settings ─────────────────────────────────────────────────────────────
    manageStoreSettings: 'Manage your store and account settings',
    storeLbl: 'Store',
    profileLbl: 'Profile',
    securityLbl: 'Security',
    notificationsLbl: 'Notifications',
    storeInformation: 'Store Information',
    updateStoreDetails: 'Update your store details and configuration',
    storeName: 'Store Name',
    currency: 'Currency',
    taxRate: 'Tax Rate (%)',
    shippingChargeLbl: 'Shipping Charge (৳)',
    saveStoreSettings: 'Save Store Settings',
    profileInfo: 'Profile Information',
    updatePersonalDetails: 'Update your personal account details',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    updateProfile: 'Update Profile',
    changePassword: 'Change Password',
    updatePasswordSecurity: 'Update your password to keep your account secure',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    passwordRequirements: 'Password Requirements:',
    atLeast8Chars: 'At least 8 characters long',
    mixLettersNumbers: 'Mix of letters and numbers recommended',
    specialChars: 'Special characters for extra security',
    notificationPreferences: 'Notification Preferences',
    manageNotificationsDesc: 'Manage how you receive notifications and alerts',
    emailNotifications: 'Email Notifications',
    receiveEmailUpdates: 'Receive email updates about important events',
    orderNotifications: 'Order Notifications',
    getNotifiedNewOrders: 'Get notified when new orders are placed',
    paymentNotifications: 'Payment Notifications',
    paymentAlertsSuccess: 'Alerts for successful and failed payments',
    lowStockNotifications: 'Low Stock Notifications',
    lowStockAlerts: 'Get alerts when products are running low on stock',
    customerNotifications: 'Customer Notifications',
    newCustomerRegistrations: 'Updates about new customer registrations',
    savePreferences: 'Save Preferences',
    // ── HomePageProduct ──────────────────────────────────────────────────────
    manageHomepageSections: 'Manage products shown in each home page section',
    seedDefaultSections: 'Seed Default Sections',
    addProductDetailSections: 'Add Product Detail Sections',
    newSection: 'New Section',
    noSectionsYet: "No sections yet. Click 'Seed Default Sections' to create the standard home page sections.",
    productDetailPage: 'Product Detail Page',
    dragToReorder: 'Drag to reorder',
    moveUp: 'Move up',
    moveDown: 'Move down',
    noProductsInSection: 'No products in this section yet.',
    editSection: 'Edit Section',
    configureSection: 'Configure how this section appears on the home page.',
    keyUnique: 'Key (unique)',
    titleBangla: 'Title (Bangla)',
    iconEmoji: 'Icon (emoji)',
    subtitle: 'Subtitle',
    layout: 'Layout',
    carousel: 'Carousel',
    grid: 'Grid',
    accentColor: 'Accent color',
    backgroundColor: 'Background color',
    editProductEntry: 'Edit Product',
    productEntryDesc: 'Product entry shown inside the section.',
    uploadImage: 'Upload Image',
    uploading: 'Uploading...',
    orPasteImageUrl: 'or paste image URL',
    slugLabel: 'Slug',
    autoGeneratedIfEmpty: 'auto-generated if empty',
    comparePrice: 'Compare price (৳)',
    unit: 'Unit',
    minQty: 'Min qty',
    linkOptional: 'Link (optional)',
    // ── ProductQA ────────────────────────────────────────────────────────────
    productQA: 'Product Q&A',
    answeredStatus: 'Answered',
    noQuestionsFound: 'No questions found',
    question: 'Question',
    answer: 'Answer',
    noAnswerYet: 'No answer yet',
    editAnswer: 'Edit Answer',
    answerQuestion: 'Answer Question',
    yourAnswer: 'Your Answer',
    typeAnswerHere: 'Type your answer here...',
    saveAnswer: 'Save Answer',
    // ── Table / Pagination ───────────────────────────────────────────────────
    showing: 'Showing',
    of: 'of',
    results: 'results',
    rowsPerPage: 'Rows per page',
    noResults: 'No results found',
    // ── Toasts / Feedback ────────────────────────────────────────────────────
    savedSuccess: 'Saved successfully',
    deletedSuccess: 'Deleted successfully',
    errorOccurred: 'An error occurred',
    // ── Language ─────────────────────────────────────────────────────────────
    language: 'Language',
    english: 'English',
    bangla: 'বাংলা',
    // ── Misc ─────────────────────────────────────────────────────────────────
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    street: 'Street',
    state: 'State',
    zipCode: 'Zip Code',
    amount: 'Amount',
    customer: 'Customer',
    type: 'Type',
    order: 'Order',
    notes: 'Notes',
    role: 'Role',
    new30d: 'New (30d)',
    totalLabel: 'Total',
    revenue: 'Revenue',
    product: 'Product',
    method: 'Method',
    vendor: 'Vendor',
    totalAmount: 'Total Amount (৳)',
    // ── ProductQA extra ──────────────────────────────────────────────────────
    questions: 'Questions',
    // ── BundleOffers ─────────────────────────────────────────────────────────
    bundleBogoOffers: 'Bundle & BOGO Offers',
    addOffer: 'Add Offer',
    noBundleOffers: 'No bundle offers yet. Create the first one!',
    editOffer: 'Edit Offer',
    addBundleOffer: 'Add Bundle / BOGO Offer',
    offerType: 'Offer Type',
    bogoOption: 'BOGO (Buy One Get One)',
    buyXGetY: 'Buy X Get Y',
    bundle: 'Bundle',
    buyProductId: 'Buy Product ID',
    buyQty: 'Buy Quantity',
    getProductId: 'Get Product ID',
    getQty: 'Get Quantity',
    getDiscountPct: 'Get Discount % (100 = free)',
    bundleProductsJson: 'Bundle Products (JSON)',
    bundlePrice: 'Bundle Price (৳)',
    fixedDiscount: 'Fixed (৳)',
    minCartValue: 'Min Cart Value (৳)',
    dates: 'Dates',
    updateOffer: 'Update Offer',
    createOffer: 'Create Offer',
  },

  bn: {
    // ── Sidebar ──────────────────────────────────────────────────────────────
    dashboard: 'ড্যাশবোর্ড',
    categories: 'ক্যাটাগরি',
    products: 'পণ্য',
    customers: 'গ্রাহক',
    orders: 'অর্ডার',
    payments: 'পেমেন্ট',
    shipping: 'শিপিং',
    shipments: 'শিপমেন্ট',
    vendors: 'বিক্রেতা',
    warehouses: 'গুদামঘর',
    couriers: 'কুরিয়ার',
    deliveryCoverage: 'ডেলিভারি কভারেজ',
    grocerySettings: 'গ্রোসারি সেটিংস',
    codSettlement: 'COD ও সেটেলমেন্ট',
    brands: 'ব্র্যান্ড',
    returns: 'রিটার্ন',
    reports: 'রিপোর্ট',
    marketing: 'মার্কেটিং',
    reviews: 'রিভিউ',
    searchAnalytics: 'সার্চ অ্যানালিটিক্স',
    liveSessions: 'লাইভ সেশন',
    vendorReviews: 'বিক্রেতা রিভিউ',
    settings: 'সেটিংস',
    homePageProduct: 'হোমপেজ পণ্য',
    logout: 'লগআউট',
    switchLanguage: 'English',
    // ── Common actions ───────────────────────────────────────────────────────
    save: 'সংরক্ষণ',
    cancel: 'বাতিল',
    delete: 'মুছুন',
    edit: 'সম্পাদনা',
    add: 'যোগ করুন',
    addNew: 'নতুন যোগ করুন',
    search: 'খুঁজুন',
    filter: 'ফিল্টার',
    filters: 'ফিল্টারসমূহ',
    clearAll: 'সব মুছুন',
    clear: 'মুছুন',
    status: 'স্ট্যাটাস',
    actions: 'কার্যক্রম',
    name: 'নাম',
    nameBnLabel: 'নাম (বাংলা)',
    description: 'বিবরণ',
    price: 'মূল্য',
    stock: 'স্টক',
    category: 'ক্যাটাগরি',
    brand: 'ব্র্যান্ড',
    sku: 'SKU',
    loading: 'লোড হচ্ছে...',
    noData: 'কোনো তথ্য পাওয়া যায়নি',
    confirm: 'নিশ্চিত করুন',
    yes: 'হ্যাঁ',
    no: 'না',
    total: 'মোট',
    active: 'সক্রিয়',
    inactive: 'নিষ্ক্রিয়',
    draft: 'ড্রাফট',
    published: 'প্রকাশিত',
    all: 'সব',
    none: 'কোনটি না',
    select: 'নির্বাচন করুন',
    upload: 'আপলোড',
    remove: 'সরান',
    view: 'দেখুন',
    close: 'বন্ধ করুন',
    update: 'আপডেট',
    create: 'তৈরি করুন',
    refresh: 'রিফ্রেশ',
    export: 'CSV রপ্তানি',
    exporting: 'রপ্তানি হচ্ছে…',
    import: 'আমদানি',
    selected: 'নির্বাচিত',
    previous: 'আগের',
    next: 'পরের',
    prev: 'আগের',
    saving: 'সংরক্ষণ হচ্ছে…',
    // ── Dashboard ────────────────────────────────────────────────────────────
    welcomeBack: 'স্বাগতম! আপনার স্টোরের সারসংক্ষেপ।',
    totalRevenue: 'মোট আয়',
    revenueOverview: 'আয়ের পর্যালোচনা',
    salesByCategory: 'ক্যাটাগরি অনুযায়ী বিক্রয়',
    ordersTrend: 'অর্ডার প্রবণতা',
    recentOrders: 'সাম্প্রতিক অর্ডার',
    loadingOrders: 'অর্ডার লোড হচ্ছে...',
    noOrdersYet: 'এখনো কোনো অর্ডার নেই',
    vsLastMonth: 'গত মাসের তুলনায়',
    inventoryValue: 'মজুদ মূল্য',
    totalOrders: 'মোট অর্ডার',
    totalCustomers: 'মোট গ্রাহক',
    totalProducts: 'মোট পণ্য',
    // ── Products ─────────────────────────────────────────────────────────────
    manageProductCatalog: 'আপনার পণ্য তালিকা পরিচালনা করুন',
    addProduct: 'পণ্য যোগ করুন',
    lowStock: 'কম স্টক',
    searchByNameOrSku: 'নাম বা SKU দিয়ে খুঁজুন...',
    statusVisibility: 'স্ট্যাটাস / দৃশ্যমানতা',
    allStatus: 'সব স্ট্যাটাস',
    outOfStock: 'স্টক শেষ',
    archived: 'আর্কাইভ করা',
    allCategories: 'সব ক্যাটাগরি',
    stockStatus: 'স্টক স্ট্যাটাস',
    allStock: 'সব স্টক',
    inStock: 'স্টকে আছে',
    priceRange: 'মূল্য পরিসীমা (৳)',
    dateFrom: 'যোগের তারিখ — থেকে',
    dateTo: 'যোগের তারিখ — পর্যন্ত',
    updateStock: 'স্টক আপডেট',
    noProductsFound: 'কোনো পণ্য পাওয়া যায়নি',
    uncategorized: 'বিভাগহীন',
    archiveProduct: 'আর্কাইভ',
    publishProduct: 'প্রকাশ করুন',
    newBadge: 'নতুন',
    // ── Product form ─────────────────────────────────────────────────────────
    addProductTitle: 'নতুন পণ্য যোগ করুন',
    editProduct: 'পণ্য সম্পাদনা',
    productNameEn: 'পণ্যের নাম (ইংরেজি) *',
    productNameBn: 'পণ্যের নাম (বাংলা)',
    urlSlug: 'URL স্লাগ *',
    descriptionEn: 'বিবরণ (ইংরেজি)',
    descriptionBn: 'বিবরণ (বাংলা)',
    shortDescEn: 'সংক্ষিপ্ত বিবরণ (ইংরেজি)',
    shortDescBn: 'সংক্ষিপ্ত বিবরণ (বাংলা)',
    regularPrice: 'নিয়মিত মূল্য *',
    salePrice: 'বিক্রয় মূল্য',
    tags: 'ট্যাগ',
    addTag: 'ট্যাগ যোগ করুন',
    images: 'ছবি',
    metaTitleEn: 'মেটা শিরোনাম (ইংরেজি)',
    metaDescriptionEn: 'মেটা বিবরণ (ইংরেজি)',
    saveProduct: 'পণ্য সংরক্ষণ করুন',
    general: 'সাধারণ',
    pricingStock: 'মূল্য ও স্টক',
    variants: 'ভেরিয়েন্ট',
    publish: 'প্রকাশ',
    related: 'সম্পর্কিত',
    seo: 'SEO',
    addVariant: 'ভেরিয়েন্ট যোগ করুন',
    variantName: 'ভেরিয়েন্ট নাম',
    variantSku: 'ভেরিয়েন্ট SKU',
    variantPrice: 'ভেরিয়েন্ট মূল্য',
    variantSalePrice: 'ভেরিয়েন্ট বিক্রয় মূল্য',
    variantStock: 'ভেরিয়েন্ট স্টক',
    barcode: 'বারকোড',
    weight: 'ওজন (কেজি)',
    lowStockThreshold: 'কম স্টক সীমা',
    featured: 'ফিচার্ড',
    isNew: 'নতুন পণ্য',
    onSale: 'সেলে আছে',
    visibility: 'দৃশ্যমানতা',
    visible: 'দৃশ্যমান',
    hidden: 'লুকানো',
    shippingClass: 'শিপিং ক্লাস',
    shippingCharge: 'শিপিং চার্জ',
    relatedProducts: 'সম্পর্কিত পণ্য',
    upsellProducts: 'আপসেল পণ্য',
    crossSellProducts: 'ক্রস-সেল পণ্য',
    // ── Categories ───────────────────────────────────────────────────────────
    manageCategoriesDesc: 'পণ্য ক্যাটাগরি পরিচালনা — ট্রি ভিউ',
    addCategory: 'ক্যাটাগরি যোগ করুন',
    trash: 'ট্র্যাশ',
    searchCategories: 'ক্যাটাগরি খুঁজুন (ইংরেজি বা বাংলা)…',
    collapseAll: 'সব বন্ধ করুন',
    expandAll: 'সব খুলুন',
    activate: 'সক্রিয় করুন',
    deactivate: 'নিষ্ক্রিয় করুন',
    trashIsEmpty: 'ট্র্যাশ খালি',
    noCategoriesYet: 'এখনো কোনো ক্যাটাগরি নেই। প্রথম ক্যাটাগরি যোগ করুন!',
    moveToTrash: 'ট্র্যাশে সরান',
    permanentlyDelete: 'স্থায়ীভাবে মুছুন?',
    restore: 'পুনরুদ্ধার করুন',
    deleteForever: 'সম্পূর্ণ মুছুন',
    addSubcategory: 'সাব-ক্যাটাগরি যোগ করুন',
    parentCategory: 'প্যারেন্ট ক্যাটাগরি',
    categoryName: 'ক্যাটাগরির নাম (ইংরেজি)',
    categoryNameBn: 'ক্যাটাগরির নাম (বাংলা)',
    categorySlug: 'ক্যাটাগরি স্লাগ',
    editCategory: 'ক্যাটাগরি সম্পাদনা',
    // ── Orders ───────────────────────────────────────────────────────────────
    manageTrackOrders: 'সব গ্রাহক অর্ডার পরিচালনা ও ট্র্যাক করুন',
    pendingOrders: 'অপেক্ষমাণ অর্ডার',
    paidOrders: 'পরিশোধিত অর্ডার',
    searchOrderOrCustomer: 'অর্ডার নম্বর বা গ্রাহক খুঁজুন…',
    allPayments: 'সব পেমেন্ট',
    setStatus: 'স্ট্যাটাস সেট করুন',
    setPayment: 'পেমেন্ট সেট করুন',
    orderNumber: 'অর্ডার নম্বর',
    items: 'পণ্য',
    tracking: 'ট্র্যাকিং',
    date: 'তারিখ',
    noOrdersFound: 'কোনো অর্ডার পাওয়া যায়নি',
    orderDetails: 'অর্ডারের বিবরণ',
    orderStatus: 'অর্ডার স্ট্যাটাস',
    paymentStatus: 'পেমেন্ট স্ট্যাটাস',
    orderDate: 'অর্ডারের তারিখ',
    paymentMethod: 'পেমেন্ট পদ্ধতি',
    shippingTracking: 'শিপিং / ট্র্যাকিং',
    shippingAddress: 'শিপিং ঠিকানা',
    orderItems: 'অর্ডার আইটেম',
    qty: 'পরিমাণ',
    subtotal: 'সাবটোটাল',
    tax: 'ট্যাক্স',
    discount: 'ছাড়',
    adminNotes: 'অ্যাডমিন নোট',
    noNotes: 'কোনো নোট নেই',
    orderTimeline: 'অর্ডার টাইমলাইন',
    viewInvoice: 'ইনভয়েস দেখুন',
    courierName: 'কুরিয়ারের নাম',
    trackingNumber: 'ট্র্যাকিং নম্বর',
    estDelivery: 'আনুমানিক ডেলিভারির তারিখ',
    saveTracking: 'ট্র্যাকিং সংরক্ষণ',
    internalNote: 'অভ্যন্তরীণ নোট লিখুন…',
    saveNote: 'নোট সংরক্ষণ',
    printInvoice: 'ইনভয়েস প্রিন্ট',
    invoice: 'ইনভয়েস',
    setTracking: 'ট্র্যাকিং সেট করুন',
    addNote: 'নোট যোগ করুন',
    markProcessing: 'প্রক্রিয়াধীন চিহ্নিত করুন',
    markDelivered: 'বিতরণ হিসেবে চিহ্নিত করুন',
    confirmed: 'নিশ্চিত',
    processing: 'প্রক্রিয়াধীন',
    shipped: 'পাঠানো হয়েছে',
    outForDelivery: 'ডেলিভারিতে আছে',
    delivered: 'বিতরণ হয়েছে',
    cancelled: 'বাতিল',
    refunded: 'ফেরত দেওয়া হয়েছে',
    paid: 'পরিশোধিত',
    failed: 'ব্যর্থ',
    pending: 'অপেক্ষমাণ',
    // ── Customers ────────────────────────────────────────────────────────────
    manageCustomerDb: 'আপনার গ্রাহক ডাটাবেস পরিচালনা করুন',
    addCustomer: 'গ্রাহক যোগ করুন',
    returning: 'পুনরায় ক্রেতা',
    avgLtv: 'গড় LTV',
    perCustomer: 'প্রতি গ্রাহক',
    avgFrequency: 'গড় ফ্রিকোয়েন্সি',
    ordersPerCustomer: 'অর্ডার / গ্রাহক',
    activeRecent: 'সক্রিয় (৯০ দিন)',
    loggedInRecently: 'সম্প্রতি লগইন করেছে',
    activeCustomers: 'সক্রিয় গ্রাহক',
    searchCustomers: 'গ্রাহক খুঁজুন...',
    blocked: 'ব্লকড',
    allGroups: 'সব গ্রুপ',
    regular: 'সাধারণ',
    wholesale: 'পাইকারি',
    vip: 'VIP',
    dealer: 'ডিলার',
    customersSelected: 'গ্রাহক নির্বাচিত',
    sendMessage: 'বার্তা পাঠান',
    contact: 'যোগাযোগ',
    group: 'গ্রুপ',
    spent: 'ব্যয়',
    points: 'পয়েন্ট',
    loadingCustomers: 'গ্রাহক লোড হচ্ছে...',
    noCustomersFound: 'কোনো গ্রাহক পাওয়া যায়নি',
    suspendedUntil: 'স্থগিত পর্যন্ত',
    changeGroup: 'গ্রুপ পরিবর্তন',
    managePoints: 'পয়েন্ট ব্যবস্থাপনা',
    suspendUntil: 'পর্যন্ত স্থগিত করুন',
    editCustomer: 'গ্রাহক সম্পাদনা',
    addNewCustomer: 'নতুন গ্রাহক যোগ করুন',
    deleteCustomer: 'গ্রাহক মুছুন',
    customerDetails: 'গ্রাহকের বিবরণ',
    profile: 'প্রোফাইল',
    security: 'নিরাপত্তা',
    messages: 'বার্তাসমূহ',
    rewardPoints: 'রিওয়ার্ড পয়েন্ট',
    totalSpent: 'মোট ব্যয়',
    lastLogin: 'শেষ লগইন',
    totalEarned: 'মোট অর্জিত',
    totalRedeemed: 'মোট ব্যবহৃত',
    available: 'পাওয়া যাচ্ছে',
    noPointsHistory: 'পয়েন্টের ইতিহাস নেই',
    wishlistEmpty: 'উইশলিস্ট খালি',
    savedAddressBook: 'সংরক্ষিত ঠিকানা বই',
    addAddress: 'ঠিকানা যোগ করুন',
    noAddressSaved: 'কোনো ঠিকানা সংরক্ষিত নেই',
    accountSecurity: 'অ্যাকাউন্ট নিরাপত্তা',
    loginHistory: 'লগইন ইতিহাস',
    resetPassword: 'পাসওয়ার্ড রিসেট',
    activationLink: 'অ্যাক্টিভেশন লিংক',
    generateLink: 'লিংক তৈরি করুন',
    noMessagesSent: 'এখনো কোনো বার্তা পাঠানো হয়নি',
    newMessage: 'নতুন বার্তা',
    importCustomers: 'গ্রাহক আমদানি করুন',
    editAddress: 'ঠিকানা সম্পাদনা',
    // ── Brands ───────────────────────────────────────────────────────────────
    searchBrands: 'ব্র্যান্ড খুঁজুন…',
    bengaliLabel: 'বাংলা',
    logoUrl: 'লোগো URL',
    bannerUrl: 'ব্যানার URL',
    website: 'ওয়েবসাইট',
    sortOrder: 'ক্রম',
    noBrandsFound: 'কোনো ব্র্যান্ড পাওয়া যায়নি',
    addBrand: 'ব্র্যান্ড যোগ করুন',
    editBrand: 'ব্র্যান্ড সম্পাদনা',
    brandName: 'ব্র্যান্ডের নাম',
    // ── Vendors ──────────────────────────────────────────────────────────────
    manageMarketplaceVendors: 'মার্কেটপ্লেস বিক্রেতা পরিচালনা করুন',
    addVendor: 'বিক্রেতা যোগ করুন',
    totalVendors: 'মোট বিক্রেতা',
    pendingApproval: 'অনুমোদনের অপেক্ষায়',
    codEnabled: 'COD সক্রিয়',
    searchVendors: 'বিক্রেতা খুঁজুন...',
    suspended: 'স্থগিত',
    location: 'অবস্থান',
    cod: 'COD',
    balance: 'ব্যালেন্স',
    approve: 'অনুমোদন করুন',
    reject: 'প্রত্যাখ্যান করুন',
    noVendorsFound: 'কোনো বিক্রেতা পাওয়া যায়নি',
    editVendor: 'বিক্রেতা সম্পাদনা',
    vendorName: 'বিক্রেতার নাম *',
    businessName: 'ব্যবসার নাম',
    district: 'জেলা',
    rejectionReason: 'প্রত্যাখ্যানের কারণ...',
    rejectVendorTitle: 'বিক্রেতা প্রত্যাখ্যান',
    recordDeposit: 'জমা রেকর্ড করুন',
    amountBdt: 'পরিমাণ (BDT) *',
    // ── Payments ─────────────────────────────────────────────────────────────
    trackManagePayments: 'পেমেন্ট লেনদেন ট্র্যাক ও পরিচালনা করুন',
    totalTransactions: 'মোট লেনদেন',
    completed: 'সম্পন্ন',
    totalReceived: 'মোট প্রাপ্ত',
    pendingAmount: 'অপেক্ষমাণ পরিমাণ',
    searchByTransactionId: 'লেনদেন আইডি দিয়ে খুঁজুন...',
    partRefunded: 'আংশিক ফেরত',
    allMethods: 'সব পদ্ধতি',
    cashOnDelivery: 'ক্যাশ অন ডেলিভারি',
    bankTransfer: 'ব্যাংক ট্রান্সফার',
    transactionId: 'লেনদেন আইডি',
    paidAt: 'পরিশোধের সময়',
    loadingPayments: 'পেমেন্ট লোড হচ্ছে...',
    noPaymentsFound: 'কোনো পেমেন্ট পাওয়া যায়নি',
    markCompleted: 'সম্পন্ন চিহ্নিত করুন',
    verifyPayment: 'পেমেন্ট যাচাই করুন',
    markFailed: 'ব্যর্থ চিহ্নিত করুন',
    issueRefund: 'ফেরত দিন',
    paymentDetails: 'পেমেন্টের বিবরণ',
    processRefund: 'ফেরত প্রক্রিয়া করুন',
    originalAmount: 'মূল পরিমাণ',
    refundType: 'ফেরতের ধরন',
    fullRefund: 'সম্পূর্ণ ফেরত',
    partialRefund: 'আংশিক ফেরত',
    refundAmount: 'ফেরতের পরিমাণ (৳)',
    reason: 'কারণ',
    // ── Shipping ─────────────────────────────────────────────────────────────
    shippingMgmt: 'শিপিং ব্যবস্থাপনা',
    manageDeliveryAreas: 'ডেলিভারি এলাকা পরিচালনা এবং শিপমেন্ট ট্র্যাক করুন',
    pendingShipment: 'অপেক্ষমাণ শিপমেন্ট',
    shippedInTransit: 'পাঠানো / পথে',
    activeAreas: 'সক্রিয় এলাকা',
    shipmentOrders: 'শিপমেন্ট অর্ডার',
    deliveryAreas: 'ডেলিভারি এলাকা',
    shippingMethods: 'শিপিং পদ্ধতি',
    searchOrders: 'অর্ডার খুঁজুন...',
    noShipmentOrders: 'কোনো শিপমেন্ট অর্ডার পাওয়া যায়নি',
    addArea: 'এলাকা যোগ করুন',
    city: 'শহর',
    freeAbove: 'উপরে বিনামূল্যে',
    estDays: 'আনুমানিক দিন',
    days: 'দিন',
    noDeliveryAreasFound: 'কোনো ডেলিভারি এলাকা পাওয়া যায়নি',
    editDeliveryArea: 'ডেলিভারি এলাকা সম্পাদনা',
    addDeliveryArea: 'ডেলিভারি এলাকা যোগ করুন',
    areaName: 'এলাকার নাম',
    deliveryCharge: 'ডেলিভারি চার্জ (৳)',
    freeDeliveryAbove: 'উপরে বিনামূল্যে ডেলিভারি',
    estimatedDeliveryDays: 'আনুমানিক ডেলিভারি দিন',
    postalCodes: 'পোস্টাল কোড (কমা দিয়ে আলাদা করুন)',
    updateArea: 'এলাকা আপডেট',
    createArea: 'এলাকা তৈরি',
    addMethod: 'পদ্ধতি যোগ করুন',
    baseCharge: 'বেস চার্জ',
    noShippingMethods: 'কোনো শিপিং পদ্ধতি কনফিগার করা হয়নি',
    editShippingMethod: 'শিপিং পদ্ধতি সম্পাদনা',
    addShippingMethod: 'শিপিং পদ্ধতি যোগ করুন',
    flatRate: 'ফ্ল্যাট রেট',
    weightBased: 'ওজন-ভিত্তিক',
    freeShipping: 'বিনামূল্যে শিপিং',
    express: 'এক্সপ্রেস',
    freeThreshold: 'বিনামূল্যে সীমা (৳)',
    updateMethod: 'পদ্ধতি আপডেট',
    createMethod: 'পদ্ধতি তৈরি',
    // ── Shipments ────────────────────────────────────────────────────────────
    trackManageShipments: 'সব শিপমেন্ট ট্র্যাক ও পরিচালনা করুন',
    inTransit: 'পথে',
    searchShipment: 'শিপমেন্ট নম্বর, অর্ডার আইডি, ট্র্যাকিং খুঁজুন...',
    readyForPickup: 'পিকআপের জন্য প্রস্তুত',
    pickedUp: 'পিক করা হয়েছে',
    failedDelivery: 'ডেলিভারি ব্যর্থ',
    returnedStatus: 'ফিরিয়ে দেওয়া হয়েছে',
    shipmentNo: 'শিপমেন্ট নম্বর',
    source: 'উৎস',
    courier: 'কুরিয়ার',
    noShipmentsFound: 'কোনো শিপমেন্ট পাওয়া যায়নি',
    pageOf: 'পৃষ্ঠা',
    shipmentDetails: 'শিপমেন্টের বিবরণ',
    deliveryChargeLbl: 'ডেলিভারি চার্জ',
    eta: 'আনুমানিক আগমনের সময়',
    trackingHistory: 'ট্র্যাকিং ইতিহাস',
    updateShipment: 'শিপমেন্ট আপডেট',
    selectCourier: 'কুরিয়ার নির্বাচন করুন...',
    noteDescription: 'নোট / বিবরণ',
    // ── Returns ──────────────────────────────────────────────────────────────
    returnRequests: 'রিটার্ন অনুরোধ',
    allTypes: 'সব ধরন',
    returnType: 'রিটার্ন',
    exchangeType: 'বিনিময়',
    returnNo: 'রিটার্ন নম্বর',
    refundAmt: 'রিফান্ড পরিমাণ',
    noReturnRequests: 'কোনো রিটার্ন অনুরোধ নেই',
    returnRequest: 'রিটার্ন অনুরোধ',
    adminNote: 'অ্যাডমিন নোট',
    updateStatus: 'স্ট্যাটাস আপডেট করুন',
    internalNoteMsg: 'অভ্যন্তরীণ নোট বা গ্রাহকের বার্তা…',
    // ── Reports ──────────────────────────────────────────────────────────────
    reportsAnalytics: 'রিপোর্ট ও বিশ্লেষণ',
    businessInsights: 'ব্যবসায়িক অন্তর্দৃষ্টি এবং পারফরম্যান্স মেট্রিক্স',
    days7: '৭ দিন',
    days30: '৩০ দিন',
    days90: '৯০ দিন',
    year1: '১ বছর',
    overview: 'সারসংক্ষেপ',
    sales: 'বিক্রয়',
    finance: 'আর্থিক',
    stockTab: 'স্টক',
    todaysRevenue: 'আজকের আয়',
    todaysOrders: 'আজকের অর্ডার',
    monthlyRevenue: 'মাসিক আয়',
    revenueTrend: 'আয়ের প্রবণতা',
    salesSummary: 'বিক্রয় সারসংক্ষেপ',
    avgOrderValue: 'গড় অর্ডার মূল্য',
    salesByPaymentMethod: 'পেমেন্ট পদ্ধতি অনুযায়ী বিক্রয়',
    noDataLabel: 'কোনো তথ্য নেই',
    ordersByStatus: 'স্ট্যাটাস অনুযায়ী অর্ডার',
    orderMetrics: 'অর্ডার মেট্রিক্স',
    cancelledOrders: 'বাতিল অর্ডার',
    refundedOrders: 'ফেরত অর্ডার',
    newLast30Days: 'নতুন (শেষ ৩০ দিন)',
    topSpenders: 'সর্বোচ্চ ব্যয়কারী',
    topCustomersBySpending: 'ব্যয় অনুযায়ী শীর্ষ গ্রাহক',
    topSellingProducts: 'সর্বাধিক বিক্রিত পণ্য',
    qtySold: 'বিক্রিত পরিমাণ',
    lowStockProducts: 'কম স্টকের পণ্য',
    noSalesData: 'কোনো বিক্রয় তথ্য নেই',
    noLowStockProducts: 'কম স্টকের পণ্য নেই',
    loadingFinanceData: 'আর্থিক তথ্য লোড হচ্ছে...',
    noFinanceData: 'কোনো আর্থিক তথ্য পাওয়া যায়নি।',
    netRevenue: 'নেট আয়',
    shippingRevenue: 'শিপিং আয়',
    discounts: 'ছাড়',
    refunds: 'ফেরত',
    pendingPayments: 'অপেক্ষমাণ পেমেন্ট',
    revenueByPaymentMethod: 'পেমেন্ট পদ্ধতি অনুযায়ী আয়',
    transactions: 'লেনদেন',
    stockValue: 'স্টকের মূল্য',
    lowStockItems: 'কম স্টকের আইটেম',
    allProductsWellStocked: 'সব পণ্যের পর্যাপ্ত স্টক আছে',
    failedToExport: 'রপ্তানি ব্যর্থ হয়েছে',
    // ── Marketing ────────────────────────────────────────────────────────────
    marketingPromotion: 'মার্কেটিং ও প্রমোশন',
    manageCouponsDesc: 'কুপন, ব্যানার এবং প্রমোশনাল ক্যাম্পেইন পরিচালনা করুন',
    activeCoupons: 'সক্রিয় কুপন',
    totalRedemptions: 'মোট ব্যবহার',
    activeBanners: 'সক্রিয় ব্যানার',
    totalCoupons: 'মোট কুপন',
    coupons: 'কুপন',
    banners: 'ব্যানার',
    flashSales: 'ফ্ল্যাশ সেল',
    emailCampaigns: 'ইমেইল ক্যাম্পেইন',
    addCoupon: 'কুপন যোগ করুন',
    code: 'কোড',
    value: 'মান',
    minPurchase: 'সর্বনিম্ন ক্রয়',
    used: 'ব্যবহৃত',
    expires: 'মেয়াদ শেষ',
    expired: 'মেয়াদ উত্তীর্ণ',
    noCouponsYet: 'এখনো কোনো কুপন নেই',
    addBanner: 'ব্যানার যোগ করুন',
    image: 'ছবি',
    title: 'শিরোনাম',
    placement: 'স্থান',
    priority: 'অগ্রাধিকার',
    noBannersYet: 'এখনো কোনো ব্যানার নেই',
    editCoupon: 'কুপন সম্পাদনা',
    createCoupon: 'কুপন তৈরি করুন',
    couponCode: 'কুপন কোড',
    discountType: 'ছাড়ের ধরন',
    discountValue: 'ছাড়ের মান',
    minPurchaseLbl: 'সর্বনিম্ন ক্রয় (৳)',
    maxDiscount: 'সর্বোচ্চ ছাড় (৳)',
    startDate: 'শুরুর তারিখ',
    endDate: 'শেষের তারিখ',
    usageLimit: 'ব্যবহারের সীমা (০ = সীমাহীন)',
    perCustomerLimit: 'প্রতি গ্রাহক সীমা',
    percentage: 'শতাংশ',
    fixedAmount: 'নির্দিষ্ট পরিমাণ',
    freeDelivery: 'বিনামূল্যে ডেলিভারি',
    updateCoupon: 'কুপন আপডেট',
    addFlashSale: 'ফ্ল্যাশ সেল যোগ করুন',
    badge: 'ব্যাজ',
    start: 'শুরু',
    end: 'শেষ',
    ended: 'শেষ হয়েছে',
    noFlashSalesYet: 'এখনো কোনো ফ্ল্যাশ সেল নেই',
    editFlashSale: 'ফ্ল্যাশ সেল সম্পাদনা',
    createFlashSale: 'ফ্ল্যাশ সেল তৈরি করুন',
    badgeLabel: 'ব্যাজ লেবেল (ঐচ্ছিক)',
    newCampaign: 'নতুন ক্যাম্পেইন',
    subject: 'বিষয়',
    audience: 'দর্শক',
    sentLabel: 'পাঠানো হয়েছে',
    noCampaignsYet: 'এখনো কোনো ক্যাম্পেইন নেই',
    editCampaign: 'ক্যাম্পেইন সম্পাদনা',
    createCampaign: 'ক্যাম্পেইন তৈরি করুন',
    allCustomersAudience: 'সব গ্রাহক',
    newCustomersAudience: 'নতুন গ্রাহক',
    inactiveAudience: 'নিষ্ক্রিয়',
    scheduled: 'নির্ধারিত',
    scheduledAt: 'নির্ধারিত সময়',
    updateCampaign: 'ক্যাম্পেইন আপডেট',
    manageProducts: 'পণ্য পরিচালনা',
    searchProductsByName: 'নাম দিয়ে পণ্য খুঁজুন...',
    productSelected: 'পণ্য নির্বাচিত',
    saveProducts: 'পণ্য সংরক্ষণ',
    editBanner: 'ব্যানার সম্পাদনা',
    createBanner: 'ব্যানার তৈরি করুন',
    imageUrl: 'ছবির URL',
    linkUrl: 'লিংক URL',
    homepageTop: 'হোমপেজ শীর্ষ',
    homepageSlider: 'হোমপেজ স্লাইডার',
    sidebar: 'সাইডবার',
    popup: 'পপআপ',
    updateBanner: 'ব্যানার আপডেট',
    deleteFlashSale: 'এই ফ্ল্যাশ সেল মুছবেন?',
    deleteCampaign: 'এই ক্যাম্পেইন মুছবেন?',
    deleteCoupon: 'এই কুপন মুছবেন?',
    // ── Reviews ──────────────────────────────────────────────────────────────
    reviewsRatings: 'রিভিউ ও রেটিং',
    manageReviewsDesc: 'গ্রাহকদের পণ্য রিভিউ পরিচালনা করুন',
    totalReviews: 'মোট রিভিউ',
    approved: 'অনুমোদিত',
    avgRating: 'গড় রেটিং',
    searchReviews: 'গ্রাহক, পণ্য বা মন্তব্য দিয়ে খুঁজুন...',
    filterByStatus: 'স্ট্যাটাস দিয়ে ফিল্টার',
    noReviewsFound: 'কোনো রিভিউ পাওয়া যায়নি',
    selectAll: 'সব নির্বাচন করুন',
    unknownProduct: 'অজানা পণ্য',
    unknown: 'অজানা',
    deleteReviewConfirm: 'এই রিভিউ মুছতে চান?',
    selectReviewsFirst: 'প্রথমে রিভিউ নির্বাচন করুন',
    rejected: 'প্রত্যাখ্যাত',
    // ── VendorReviews ────────────────────────────────────────────────────────
    noVendorReviewsFound: 'কোনো বিক্রেতা রিভিউ পাওয়া যায়নি',
    reviewedBy: 'রিভিউ করেছেন',
    // ── SearchAnalytics ──────────────────────────────────────────────────────
    popularSearches: 'জনপ্রিয় সার্চ (সর্বকালের)',
    noSearchDataYet: 'এখনো কোনো সার্চ তথ্য নেই',
    trendingNow: 'এখন ট্রেন্ডিং (২৪ ঘণ্টা)',
    noTrendingSearches: 'গত ২৪ ঘণ্টায় কোনো ট্রেন্ডিং সার্চ নেই',
    // ── LiveSessions ─────────────────────────────────────────────────────────
    liveShoppingSessions: 'লাইভ শপিং সেশন',
    noLiveSessionsYet: 'এখনো কোনো লাইভ সেশন নেই',
    vendorsCanCreateSessions: 'বিক্রেতারা তাদের প্যানেল থেকে সেশন তৈরি করতে পারেন',
    store: 'স্টোর',
    viewers: 'দর্শক',
    liveStatus: 'লাইভ',
    scheduledStatus: 'নির্ধারিত',
    endedStatus: 'শেষ হয়েছে',
    // ── Couriers ─────────────────────────────────────────────────────────────
    manageCouriersDesc: 'তৃতীয় পক্ষের ডেলিভারি পার্টনার পরিচালনা করুন',
    addCourier: 'কুরিয়ার যোগ করুন',
    trackingUrlTemplate: 'ট্র্যাকিং URL টেমপ্লেট',
    noCouriersFound: 'কোনো কুরিয়ার পাওয়া যায়নি',
    editCourier: 'কুরিয়ার সম্পাদনা',
    courierCode: 'কোড (যেমন: redx, pathao)',
    trackingUrlHint: 'ট্র্যাকিং URL টেমপ্লেট ({tracking} ব্যবহার করুন)',
    // ── Warehouses ───────────────────────────────────────────────────────────
    manageWarehousesDesc: 'গুদামঘরের অবস্থান পরিচালনা করুন',
    addWarehouse: 'গুদামঘর যোগ করুন',
    noWarehouses: 'কোনো গুদামঘর নেই',
    editWarehouse: 'গুদামঘর সম্পাদনা',
    defaultLbl: 'ডিফল্ট',
    division: 'বিভাগ',
    contactName: 'যোগাযোগের নাম',
    contactPhone: 'যোগাযোগের ফোন',
    setAsDefaultWarehouse: 'ডিফল্ট গুদামঘর হিসেবে সেট করুন',
    // ── DeliveryCoverage ─────────────────────────────────────────────────────
    manageGroceryDelivery: 'গ্রোসারি ডেলিভারি এলাকা এবং শিপিং নীতি পরিচালনা করুন',
    groceryCoverage: 'গ্রোসারি কভারেজ',
    shippingPolicies: 'শিপিং নীতি',
    groceryDeliveryLimited: 'গ্রোসারি ডেলিভারি শুধুমাত্র ঢাকা শহর এলাকায় সীমিত। পৃথক এলাকা সক্রিয়/নিষ্ক্রিয় করুন।',
    noAreasAdded: 'কোনো এলাকা যোগ করা হয়নি',
    weightBasedShipping: 'সারাদেশে ডেলিভারির জন্য ওজন-ভিত্তিক শিপিং চার্জ।',
    addPolicy: 'নীতি যোগ করুন',
    areaZone: 'এলাকা / অঞ্চল',
    extraPerKg: 'অতিরিক্ত / কেজি',
    insideCity: 'শহরের ভেতরে',
    nationwide: 'সারাদেশ',
    noPoliciesFound: 'কোনো নীতি পাওয়া যায়নি',
    editArea: 'এলাকা সম্পাদনা',
    addDeliveryAreaTitle: 'ডেলিভারি এলাকা যোগ করুন',
    areaNameEnglish: 'এলাকার নাম (ইংরেজি) *',
    areaNameBengali: 'এলাকার নাম (বাংলা)',
    editShippingPolicy: 'শিপিং নীতি সম্পাদনা',
    addShippingPolicy: 'শিপিং নীতি যোগ করুন',
    zoneAreaName: 'অঞ্চল / এলাকার নাম',
    insideCityFaster: 'শহরের ভেতরে (দ্রুত ডেলিভারি)',
    baseWeight: 'বেস ওজন (কেজি)',
    baseChargeLbl: 'বেস চার্জ (৳)',
    extraPerKgLbl: 'অতিরিক্ত প্রতি কেজি (৳)',
    freeThresholdLbl: 'বিনামূল্যে সীমা (৳)',
    etaMin: 'সর্বনিম্ন ETA (দিন)',
    etaMax: 'সর্বোচ্চ ETA (দিন)',
    optional: 'ঐচ্ছিক',
    // ── GrocerySettings ──────────────────────────────────────────────────────
    configureDelivery: 'ডেলিভারি সময় স্লট এবং গ্রোসারি ডেলিভারি সেটিংস কনফিগার করুন',
    deliveryTimeSlots: 'ডেলিভারি সময় স্লট',
    addSlot: 'স্লট যোগ করুন',
    label: 'লেবেল',
    timeWindow: 'সময় উইন্ডো',
    maxOrders: 'সর্বোচ্চ অর্ডার',
    unlimited: 'সীমাহীন',
    noSlotsConfigured: 'কোনো স্লট কনফিগার করা হয়নি',
    generalSettings: 'সাধারণ সেটিংস',
    minPrepTime: 'সর্বনিম্ন প্রস্তুতির সময় (ঘণ্টা)',
    deliveryDaysAvailable: 'ডেলিভারি দিন উপলব্ধ (১ = শুধু আজ, ২ = আজ + আগামীকাল)',
    groceryDeliveryEnabled: 'গ্রোসারি ডেলিভারি সক্রিয় (১ = হ্যাঁ, ০ = না)',
    freeDeliveryMinOrder: 'বিনামূল্যে ডেলিভারির সর্বনিম্ন অর্ডার পরিমাণ (৳)',
    insideCityCharge: 'শহরের ভেতরে ডেলিভারি চার্জ (৳)',
    outsideCityCharge: 'শহরের বাইরে ডেলিভারি চার্জ (৳)',
    saveSettings: 'সেটিংস সংরক্ষণ করুন',
    editSlot: 'স্লট সম্পাদনা',
    addTimeSlot: 'সময় স্লট যোগ করুন',
    startTime: 'শুরুর সময় *',
    endTime: 'শেষের সময় *',
    maxOrdersBlank: 'সর্বোচ্চ অর্ডার (সীমাহীনের জন্য খালি রাখুন)',
    // ── CodSettlement ────────────────────────────────────────────────────────
    manageCodCollections: 'ক্যাশ-অন-ডেলিভারি সংগ্রহ এবং বিক্রেতা সেটেলমেন্ট পরিচালনা করুন',
    allVendors: 'সব বিক্রেতা',
    newSettlement: 'নতুন সেটেলমেন্ট',
    pendingCodCollection: 'অপেক্ষমাণ COD সংগ্রহ',
    pendingSettlements: 'অপেক্ষমাণ সেটেলমেন্ট',
    codTransactions: 'COD লেনদেন',
    settlementRecords: 'সেটেলমেন্ট রেকর্ড',
    collectedAt: 'সংগ্রহের সময়',
    markCollected: 'সংগৃহীত চিহ্নিত করুন',
    noCodTransactions: 'কোনো COD লেনদেন নেই',
    period: 'সময়কাল',
    platformFee: 'প্ল্যাটফর্ম ফি',
    netPayout: 'নেট পেআউট',
    processSettle: 'প্রক্রিয়া করুন',
    noSettlementRecords: 'কোনো সেটেলমেন্ট রেকর্ড নেই',
    newSettlementRecord: 'নতুন সেটেলমেন্ট রেকর্ড',
    periodStart: 'সময়কাল শুরু *',
    periodEnd: 'সময়কাল শেষ *',
    codAmountLbl: 'COD পরিমাণ (৳)',
    platformFeeLbl: 'প্ল্যাটফর্ম ফি (৳)',
    createSettlement: 'সেটেলমেন্ট তৈরি করুন',
    processSettlementTitle: 'সেটেলমেন্ট প্রক্রিয়া করুন',
    deductedFromWallet: 'এই পরিমাণ বিক্রেতার ওয়ালেট থেকে কাটা হবে।',
    paymentMethodLbl: 'পেমেন্ট পদ্ধতি',
    paymentReference: 'পেমেন্ট রেফারেন্স',
    paymentReferenceHint: 'লেনদেন আইডি',
    confirmProcess: 'নিশ্চিত করুন ও প্রক্রিয়া করুন',
    // ── Settings ─────────────────────────────────────────────────────────────
    manageStoreSettings: 'আপনার স্টোর এবং অ্যাকাউন্ট সেটিংস পরিচালনা করুন',
    storeLbl: 'স্টোর',
    profileLbl: 'প্রোফাইল',
    securityLbl: 'নিরাপত্তা',
    notificationsLbl: 'নোটিফিকেশন',
    storeInformation: 'স্টোরের তথ্য',
    updateStoreDetails: 'আপনার স্টোরের বিবরণ এবং কনফিগারেশন আপডেট করুন',
    storeName: 'স্টোরের নাম',
    currency: 'মুদ্রা',
    taxRate: 'ট্যাক্সের হার (%)',
    shippingChargeLbl: 'শিপিং চার্জ (৳)',
    saveStoreSettings: 'স্টোর সেটিংস সংরক্ষণ',
    profileInfo: 'প্রোফাইল তথ্য',
    updatePersonalDetails: 'আপনার ব্যক্তিগত অ্যাকাউন্টের বিবরণ আপডেট করুন',
    fullName: 'পূর্ণ নাম',
    phoneNumber: 'ফোন নম্বর',
    updateProfile: 'প্রোফাইল আপডেট',
    changePassword: 'পাসওয়ার্ড পরিবর্তন',
    updatePasswordSecurity: 'আপনার অ্যাকাউন্ট সুরক্ষিত রাখতে পাসওয়ার্ড আপডেট করুন',
    currentPassword: 'বর্তমান পাসওয়ার্ড',
    newPassword: 'নতুন পাসওয়ার্ড',
    confirmNewPassword: 'নতুন পাসওয়ার্ড নিশ্চিত করুন',
    passwordRequirements: 'পাসওয়ার্ডের প্রয়োজনীয়তা:',
    atLeast8Chars: 'কমপক্ষে ৮টি অক্ষর',
    mixLettersNumbers: 'অক্ষর এবং সংখ্যার মিশ্রণ প্রস্তাবিত',
    specialChars: 'অতিরিক্ত নিরাপত্তার জন্য বিশেষ অক্ষর',
    notificationPreferences: 'নোটিফিকেশন পছন্দ',
    manageNotificationsDesc: 'কীভাবে নোটিফিকেশন পাবেন তা পরিচালনা করুন',
    emailNotifications: 'ইমেইল নোটিফিকেশন',
    receiveEmailUpdates: 'গুরুত্বপূর্ণ ঘটনার ইমেইল আপডেট পান',
    orderNotifications: 'অর্ডার নোটিফিকেশন',
    getNotifiedNewOrders: 'নতুন অর্ডার হলে জানান',
    paymentNotifications: 'পেমেন্ট নোটিফিকেশন',
    paymentAlertsSuccess: 'সফল এবং ব্যর্থ পেমেন্টের জন্য সতর্কতা',
    lowStockNotifications: 'কম স্টক নোটিফিকেশন',
    lowStockAlerts: 'পণ্যের স্টক কম হলে সতর্কতা পান',
    customerNotifications: 'গ্রাহক নোটিফিকেশন',
    newCustomerRegistrations: 'নতুন গ্রাহক নিবন্ধনের আপডেট',
    savePreferences: 'পছন্দ সংরক্ষণ',
    // ── HomePageProduct ──────────────────────────────────────────────────────
    manageHomepageSections: 'হোমপেজের প্রতিটি সেকশনে দেখানো পণ্য পরিচালনা করুন',
    seedDefaultSections: 'ডিফল্ট সেকশন তৈরি করুন',
    addProductDetailSections: 'পণ্য বিবরণ সেকশন যোগ করুন',
    newSection: 'নতুন সেকশন',
    noSectionsYet: "এখনো কোনো সেকশন নেই। 'ডিফল্ট সেকশন তৈরি করুন' ক্লিক করুন।",
    productDetailPage: 'পণ্য বিবরণ পৃষ্ঠা',
    dragToReorder: 'টেনে পুনর্বিন্যাস করুন',
    moveUp: 'উপরে সরান',
    moveDown: 'নিচে সরান',
    noProductsInSection: 'এই সেকশনে এখনো কোনো পণ্য নেই।',
    editSection: 'সেকশন সম্পাদনা',
    configureSection: 'এই সেকশন হোমপেজে কীভাবে দেখাবে তা কনফিগার করুন।',
    keyUnique: 'কী (অনন্য)',
    titleBangla: 'শিরোনাম (বাংলা)',
    iconEmoji: 'আইকন (ইমোজি)',
    subtitle: 'সাবটাইটেল',
    layout: 'লেআউট',
    carousel: 'ক্যারোসেল',
    grid: 'গ্রিড',
    accentColor: 'অ্যাকসেন্ট রঙ',
    backgroundColor: 'পটভূমির রঙ',
    editProductEntry: 'পণ্য সম্পাদনা',
    productEntryDesc: 'সেকশনের ভেতরে দেখানো পণ্যের এন্ট্রি।',
    uploadImage: 'ছবি আপলোড',
    uploading: 'আপলোড হচ্ছে...',
    orPasteImageUrl: 'বা ছবির URL পেস্ট করুন',
    slugLabel: 'স্লাগ',
    autoGeneratedIfEmpty: 'খালি থাকলে স্বয়ংক্রিয়ভাবে তৈরি হবে',
    comparePrice: 'তুলনামূলক মূল্য (৳)',
    unit: 'একক',
    minQty: 'সর্বনিম্ন পরিমাণ',
    linkOptional: 'লিংক (ঐচ্ছিক)',
    // ── ProductQA ────────────────────────────────────────────────────────────
    productQA: 'পণ্য প্রশ্ন ও উত্তর',
    answeredStatus: 'উত্তর দেওয়া হয়েছে',
    noQuestionsFound: 'কোনো প্রশ্ন পাওয়া যায়নি',
    question: 'প্রশ্ন',
    answer: 'উত্তর',
    noAnswerYet: 'এখনো উত্তর নেই',
    editAnswer: 'উত্তর সম্পাদনা',
    answerQuestion: 'প্রশ্নের উত্তর দিন',
    yourAnswer: 'আপনার উত্তর',
    typeAnswerHere: 'এখানে আপনার উত্তর লিখুন...',
    saveAnswer: 'উত্তর সংরক্ষণ করুন',
    // ── Table / Pagination ───────────────────────────────────────────────────
    showing: 'দেখানো হচ্ছে',
    of: 'এর মধ্যে',
    results: 'ফলাফল',
    rowsPerPage: 'প্রতি পৃষ্ঠায় সারি',
    noResults: 'কোনো ফলাফল পাওয়া যায়নি',
    // ── Toasts / Feedback ────────────────────────────────────────────────────
    savedSuccess: 'সফলভাবে সংরক্ষণ হয়েছে',
    deletedSuccess: 'সফলভাবে মুছে ফেলা হয়েছে',
    errorOccurred: 'একটি সমস্যা হয়েছে',
    // ── Language ─────────────────────────────────────────────────────────────
    language: 'ভাষা',
    english: 'English',
    bangla: 'বাংলা',
    // ── Misc ─────────────────────────────────────────────────────────────────
    email: 'ইমেইল',
    phone: 'ফোন',
    address: 'ঠিকানা',
    street: 'রাস্তা',
    state: 'রাজ্য',
    zipCode: 'জিপ কোড',
    amount: 'পরিমাণ',
    customer: 'গ্রাহক',
    type: 'ধরন',
    order: 'অর্ডার',
    notes: 'নোট',
    role: 'ভূমিকা',
    new30d: 'নতুন (৩০ দিন)',
    totalLabel: 'মোট',
    revenue: 'আয়',
    product: 'পণ্য',
    method: 'পদ্ধতি',
    vendor: 'বিক্রেতা',
    totalAmount: 'মোট পরিমাণ (৳)',
    // ── ProductQA extra ──────────────────────────────────────────────────────
    questions: 'প্রশ্নসমূহ',
    // ── BundleOffers ─────────────────────────────────────────────────────────
    bundleBogoOffers: 'বান্ডেল ও বোগো অফার',
    addOffer: 'অফার যোগ করুন',
    noBundleOffers: 'এখনো কোনো বান্ডেল অফার নেই। প্রথমটি তৈরি করুন!',
    editOffer: 'অফার সম্পাদনা',
    addBundleOffer: 'বান্ডেল / বোগো অফার যোগ করুন',
    offerType: 'অফারের ধরন',
    bogoOption: 'বোগো (একটি কিনলে একটি বিনামূল্যে)',
    buyXGetY: 'X টি কিনলে Y টি পাবেন',
    bundle: 'বান্ডেল',
    buyProductId: 'কেনার পণ্য আইডি',
    buyQty: 'ক্রয়ের পরিমাণ',
    getProductId: 'পাওয়ার পণ্য আইডি',
    getQty: 'পাওয়ার পরিমাণ',
    getDiscountPct: 'ছাড়ের শতাংশ (১০০ = বিনামূল্যে)',
    bundleProductsJson: 'বান্ডেল পণ্যসমূহ (JSON)',
    bundlePrice: 'বান্ডেল মূল্য (৳)',
    fixedDiscount: 'নির্দিষ্ট (৳)',
    minCartValue: 'সর্বনিম্ন কার্ট মূল্য (৳)',
    dates: 'তারিখ',
    updateOffer: 'অফার আপডেট করুন',
    createOffer: 'অফার তৈরি করুন',
  },
} as const;

type TranslationKey = keyof typeof translations.en;

interface LanguageContextValue {
  language: 'en' | 'bn';
  toggleLanguage: () => void;
  getCatName: (cat: { name?: string; nameBn?: string } | null | undefined) => string;
  t: (key: TranslationKey | string) => string;
}

const LanguageContext = createContext<LanguageContextValue>({
  language: 'bn',
  toggleLanguage: () => {},
  getCatName: (cat) => cat?.name || '',
  t: (key) => key as string,
});

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<'en' | 'bn'>(() => {
    return (localStorage.getItem('adminPreferredLanguage') as 'en' | 'bn') || 'bn';
  });

  useEffect(() => {
    localStorage.setItem('adminPreferredLanguage', language);
  }, [language]);

  const toggleLanguage = () => setLanguage(prev => prev === 'en' ? 'bn' : 'en');

  const getCatName = (cat: { name?: string; nameBn?: string } | null | undefined): string => {
    if (!cat) return '';
    return language === 'bn' && cat.nameBn ? cat.nameBn : (cat.name || '');
  };

  const t = useCallback((key: string): string => {
    const dict = translations[language] as Record<string, string>;
    if (dict[key] !== undefined) return dict[key];
    const fallback = translations.en as Record<string, string>;
    return fallback[key] ?? key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, getCatName, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
