import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

// ====================== TRANSLATIONS ======================
const translations = {
  bn: {
    // === Navbar ===
    nav_findJobs: 'চাকরি খুঁজুন',
    nav_savedJobs: 'সংরক্ষিত চাকরি',
    nav_dashboard: 'ড্যাশবোর্ড',
    nav_logout: 'লগআউট',
    nav_login: 'লগইন',
    nav_postJob: 'চাকরি পোস্ট করুন',
    nav_register: 'রেজিস্ট্রেশন',

    // === Hero / JobListingPage ===
    hero_tag: '🇧🇩 Sholok Jobs — বাংলাদেশের #১ চাকরির পোর্টাল',
    hero_title1: 'আপনার স্বপ্নের',
    hero_title2: 'চাকরি খুঁজুন',
    hero_subtitle: 'হাজারো চাকরির সুযোগ থেকে বেছে নিন আপনার পছন্দের ক্যারিয়ার',
    hero_searchPlaceholder: 'পদের নাম, কোম্পানি, বা দক্ষতা লিখুন...',
    hero_allDistricts: '📍 সকল জেলা',
    hero_searchBtn: 'খুঁজুন',
    hero_activeJobs: 'সক্রিয় পদ',
    hero_companies: 'কোম্পানি',
    hero_successfulHires: 'সফল নিয়োগ',
    hero_successfulHiresCount: '১০,০০০+',

    // === Filters ===
    filter_title: 'ফিল্টার করুন',
    filter_clearAll: 'সব মুছুন',
    filter_jobType: 'চাকরির ধরন',
    filter_salaryRange: 'বেতন পরিসীমা',
    filter_district: 'জেলা',
    filter_allDistricts: 'সকল জেলা',
    filter_fullTime: 'পূর্ণকালীন',
    filter_partTime: 'পার্টটাইম / ফ্রিল্যান্স',
    filter_contract: 'চুক্তিভিত্তিক',
    filter_below30k: '৩০,০০০ টাকার নিচে',
    filter_30to60k: '৩০,০০০ - ৬০,০০০ টাকা',
    filter_above60k: '৬০,০০০+ টাকা',
    filter_btn: 'ফিল্টার',

    // === Sort ===
    sort_latest: 'সর্বশেষ পোস্ট',
    sort_salary: 'সর্বোচ্চ বেতন',
    sort_featured: 'ফিচার্ড আগে',

    // === Job Listing ===
    jobs_found: 'টি চাকরি পাওয়া গেছে',
    jobs_featured: '⭐ ফিচার্ড চাকরি',
    jobs_all: '📋 সকল চাকরি',
    jobs_loading: 'লোড হচ্ছে...',
    jobs_noResults: 'কোনো চাকরি পাওয়া যায়নি',
    jobs_noResultsSub: 'অন্য কীওয়ার্ড দিয়ে খুঁজুন বা ফিল্টার পরিবর্তন করুন',
    jobs_clearFilter: 'ফিল্টার মুছুন',

    // === Job Card ===
    card_urgent: '⚡ জরুরি',
    card_featured: '⭐ ফিচার্ড',
    card_deadline: 'শেষ তারিখ:',
    card_viewDetails: 'বিস্তারিত দেখুন →',
    card_save: 'সংরক্ষণ করুন',
    card_unsave: 'সংরক্ষণ বাতিল',

    // === Job Detail ===
    detail_home: 'হোম',
    detail_jobs: 'চাকরি',
    detail_urgentHiring: '⚡ জরুরি নিয়োগ',
    detail_featured: '⭐ ফিচার্ড',
    detail_positions: 'টি পদ',
    detail_location: 'অবস্থান',
    detail_salary: 'বেতন',
    detail_experience: 'অভিজ্ঞতা',
    detail_deadline: 'শেষ তারিখ',
    detail_applyNow: 'এখনই আবেদন করুন →',
    detail_saved: 'সংরক্ষিত',
    detail_save: 'সংরক্ষণ করুন',
    detail_description: 'চাকরির বিবরণ',
    detail_skills: 'প্রয়োজনীয় দক্ষতা',
    detail_requirements: 'শিক্ষাগত যোগ্যতা ও অভিজ্ঞতা',
    detail_benefits: 'সুযোগ-সুবিধা',
    detail_companyProfile: 'কোম্পানির প্রোফাইল দেখুন',
    detail_applyToday: 'আজই আবেদন করুন!',
    detail_applyBeforeDeadline: 'শেষ তারিখের আগে আবেদন করুন',
    detail_deadlineLabel: 'শেষ তারিখ:',
    detail_fillForm: 'আবেদন ফর্ম পূরণ করুন',
    detail_notFound: 'চাকরি খুঁজে পাওয়া যায়নি 😢',
    detail_goBack: '← ফিরে যান',
    detail_review: 'রিভিউ',

    // === Company Profile ===
    company_notFound: 'কোম্পানি খুঁজে পাওয়া যায়নি',
    company_goBack: '← ফিরে যান',
    company_about: 'কোম্পানি সম্পর্কে',
    company_benefits: 'কর্মীদের সুযোগ-সুবিধা',
    company_activeJobs: 'সক্রিয় চাকরির পদ',
    company_openPositions: 'টি পদ খালি',
    company_noJobs: 'এই মুহূর্তে কোনো খালি পদ নেই।',
    company_quickFacts: 'দ্রুত তথ্য',
    company_industry: 'শিল্প',
    company_employees: 'কর্মী সংখ্যা',
    company_founded: 'প্রতিষ্ঠা সাল',
    company_headquarters: 'সদর দফতর',
    company_website: 'ওয়েবসাইট',
    company_satisfaction: 'কর্মী সন্তুষ্টি',
    company_reviewCount: 'জন কর্মীর মতামত',
    company_established: 'প্রতিষ্ঠিত:',
    company_workEnvironment: 'কর্মপরিবেশ',
    company_careerGrowth: 'ক্যারিয়ার বৃদ্ধি',
    company_salaryBenefits: 'বেতন ও সুবিধা',
    company_workLifeBalance: 'ওয়ার্ক-লাইফ ব্যালেন্স',

    // === Apply Form ===
    apply_step1: 'ব্যক্তিগত তথ্য',
    apply_step2: 'শিক্ষা ও অভিজ্ঞতা',
    apply_step3: 'নথিপত্র',
    apply_step4: 'নিশ্চিতকরণ',
    apply_notFound: 'এই চাকরিটি খুঁজে পাওয়া যায়নি',
    apply_goBack: '← ফিরে যান',
    apply_fullName: 'পূর্ণ নাম *',
    apply_namePlaceholder: 'আপনার পূর্ণ নাম লিখুন',
    apply_mobile: 'মোবাইল নম্বর *',
    apply_email: 'ইমেইল ঠিকানা *',
    apply_nid: 'জাতীয় পরিচয়পত্র নম্বর',
    apply_nidPlaceholder: 'NID নম্বর (ঐচ্ছিক)',
    apply_gender: 'লিঙ্গ *',
    apply_selectGender: 'নির্বাচন করুন',
    apply_male: 'পুরুষ',
    apply_female: 'মহিলা',
    apply_other: 'অন্যান্য',
    apply_dob: 'জন্ম তারিখ',
    apply_district: 'জেলা *',
    apply_selectDistrict: 'জেলা নির্বাচন করুন',
    apply_address: 'বর্তমান ঠিকানা',
    apply_addressPlaceholder: 'বর্তমান ঠিকানা লিখুন',
    apply_education: 'সর্বোচ্চ শিক্ষাগত যোগ্যতা *',
    apply_selectEducation: 'নির্বাচন করুন',
    apply_institution: 'প্রতিষ্ঠানের নাম *',
    apply_institutionPlaceholder: 'বিশ্ববিদ্যালয়/কলেজের নাম',
    apply_passingYear: 'পাসের বছর *',
    apply_cgpa: 'CGPA / GPA',
    apply_educationSection: 'শিক্ষাগত যোগ্যতা',
    apply_experienceSection: 'কর্মঅভিজ্ঞতা (যদি থাকে)',
    apply_prevCompany: 'সর্বশেষ কোম্পানির নাম',
    apply_prevDesignation: 'পদবী',
    apply_totalExp: 'মোট অভিজ্ঞতা (বছর)',
    apply_prevSalary: 'সর্বশেষ বেতন (টাকা)',
    apply_coverLetter: 'কভার লেটার *',
    apply_coverLetterTitle: 'কভার লেটার ও পোর্টফোলিও',
    apply_portfolio: 'পোর্টফোলিও / LinkedIn URL',
    apply_cvUpload: 'CV / Resume আপলোড করুন',
    apply_cvFormat: 'PDF, DOC, DOCX — সর্বোচ্চ ৫ MB',
    apply_chooseFile: 'ফাইল বেছে নিন',
    apply_confirmTitle: 'আবেদন নিশ্চিত করুন',
    apply_summary: 'আবেদনের সারসংক্ষেপ',
    apply_confirmName: 'নাম',
    apply_confirmMobile: 'মোবাইল',
    apply_confirmEmail: 'ইমেইল',
    apply_confirmDistrict: 'জেলা',
    apply_confirmEducation: 'শিক্ষা',
    apply_confirmInstitution: 'প্রতিষ্ঠান',
    apply_confirmPosition: 'পদের নাম',
    apply_confirmCompany: 'কোম্পানি',
    apply_agreeText: 'আমি নিশ্চিত করছি যে উপরের সকল তথ্য সঠিক এবং আমি এই চাকরিতে আবেদন করতে সম্মত।',
    apply_next: 'পরবর্তী →',
    apply_prev: '← পূর্ববর্তী',
    apply_submit: 'আবেদন জমা দিন ✓',
    apply_successTitle: 'আবেদন সফলভাবে জমা হয়েছে!',
    apply_successSub1: '-এ',
    apply_successSub2: 'পদের জন্য আপনার আবেদন পাওয়া গেছে।',
    apply_successEmail: 'আপনার ইমেইলে',
    apply_successEmailSuffix: 'একটি নিশ্চিতকরণ পাঠানো হয়েছে।',
    apply_successContact: 'কোম্পানি শীঘ্রই যোগাযোগ করবে।',
    apply_moreJobs: 'আরও চাকরি দেখুন',
    apply_savedJobs: 'সংরক্ষিত চাকরি',
    apply_chars: 'অক্ষর',
    apply_freshGrad: 'তাজা স্নাতক (০ বছর)',
    apply_year1: '১ বছর',
    apply_year2: '২ বছর',
    apply_year3: '৩ বছর',
    apply_year45: '৪-৫ বছর',
    apply_year5plus: '৫+ বছর',

    // Validation
    val_nameRequired: 'নাম আবশ্যক',
    val_invalidPhone: 'সঠিক মোবাইল নম্বর দিন (01XXXXXXXXX)',
    val_invalidEmail: 'সঠিক ইমেইল দিন',
    val_genderRequired: 'লিঙ্গ নির্বাচন করুন',
    val_districtRequired: 'জেলা নির্বাচন করুন',
    val_educationRequired: 'সর্বোচ্চ শিক্ষাগত যোগ্যতা নির্বাচন করুন',
    val_institutionRequired: 'প্রতিষ্ঠানের নাম দিন',
    val_yearRequired: 'পাসের বছর দিন',
    val_coverLetterMin: 'কভার লেটার কমপক্ষে ৫০ অক্ষরের হতে হবে',
    val_agreeRequired: 'আবেদন করতে সম্মত হন',

    // === Saved Jobs Page ===
    saved_title: 'সংরক্ষিত চাকরি',
    saved_countSuffix: 'টি চাকরি সংরক্ষণ করেছেন',
    saved_countPrefix: 'আপনি',
    saved_empty: 'আপনার পছন্দের চাকরি সংরক্ষণ করুন',
    saved_clearAll: 'সব মুছুন',
    saved_noSaved: 'কোনো সংরক্ষিত চাকরি নেই',
    saved_noSavedSub: 'চাকরি কার্ডের বুকমার্ক আইকনে ক্লিক করে পছন্দের চাকরি সংরক্ষণ করুন',
    saved_findJobs: 'চাকরি খুঁজুন →',
    saved_browserNote: 'সংরক্ষিত চাকরিগুলো শুধুমাত্র এই ব্রাউজারে থাকবে।',
    saved_browseMore: 'আরও চাকরি দেখুন →',

    // === Login / Register ===
    auth_loginTitle: 'আপনার অ্যাকাউন্টে লগইন করুন',
    auth_email: 'ইমেইল',
    auth_password: 'পাসওয়ার্ড',
    auth_loginBtn: 'লগইন করুন',
    auth_loginWait: 'অপেক্ষা করুন...',
    auth_loginFailed: 'লগইন ব্যর্থ হয়েছে',
    auth_noAccount: 'অ্যাকাউন্ট নেই?',
    auth_register: 'রেজিস্ট্রেশন করুন',
    auth_registerTitle: 'নতুন অ্যাকাউন্ট তৈরি করুন',
    auth_whoAreYou: 'আপনি কে?',
    auth_jobSeeker: '🔍 চাকরি প্রার্থী',
    auth_employer: '🏢 নিয়োগকর্তা',
    auth_fullName: 'পূর্ণ নাম *',
    auth_namePlaceholder: 'আপনার নাম',
    auth_emailPlaceholder: 'your@email.com',
    auth_companyName: 'কোম্পানির নাম *',
    auth_companyPlaceholder: 'আপনার কোম্পানির নাম',
    auth_mobile: 'মোবাইল নম্বর',
    auth_passwordLabel: 'পাসওয়ার্ড *',
    auth_passwordPlaceholder: 'কমপক্ষে ৬ অক্ষর',
    auth_confirmPassword: 'পাসওয়ার্ড নিশ্চিত *',
    auth_confirmPlaceholder: 'পুনরায় লিখুন',
    auth_registerBtn: 'রেজিস্ট্রেশন করুন',
    auth_registerWait: 'অপেক্ষা করুন...',
    auth_registerFailed: 'রেজিস্ট্রেশন ব্যর্থ হয়েছে',
    auth_hasAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    auth_loginLink: 'লগইন করুন',
    auth_passwordMismatch: 'পাসওয়ার্ড মিলছে না',
    auth_companyRequired: 'ভেন্ডরের জন্য কোম্পানির নাম আবশ্যক',

    // === Footer ===
    footer_tagline: 'বাংলাদেশের সেরা চাকরির পোর্টাল।\nআপনার স্বপ্নের চাকরি খুঁজুন।',
    footer_jobSeekers: 'চাকরি প্রার্থী',
    footer_findJobs: 'চাকরি খুঁজুন',
    footer_savedJobs: 'সংরক্ষিত চাকরি',
    footer_careerTips: 'ক্যারিয়ার টিপস',
    footer_createCV: 'সিভি তৈরি করুন',
    footer_employers: 'নিয়োগকর্তা',
    footer_postJob: 'চাকরি পোস্ট করুন',
    footer_cvDatabase: 'CV ডাটাবেস',
    footer_premiumPlan: 'প্রিমিয়াম প্ল্যান',
    footer_contact: 'যোগাযোগ',

    // === Language ===
    lang_bn: 'বাংলা',
    lang_en: 'English',
  },

  en: {
    // === Navbar ===
    nav_findJobs: 'Find Jobs',
    nav_savedJobs: 'Saved Jobs',
    nav_dashboard: 'Dashboard',
    nav_logout: 'Logout',
    nav_login: 'Login',
    nav_postJob: 'Post a Job',
    nav_register: 'Register',

    // === Hero / JobListingPage ===
    hero_tag: '🇧🇩 Sholok Jobs — Bangladesh\'s #1 Job Portal',
    hero_title1: 'Find Your',
    hero_title2: 'Dream Job',
    hero_subtitle: 'Choose your preferred career from thousands of job opportunities',
    hero_searchPlaceholder: 'Job title, company, or skill...',
    hero_allDistricts: '📍 All Districts',
    hero_searchBtn: 'Search',
    hero_activeJobs: 'Active Jobs',
    hero_companies: 'Companies',
    hero_successfulHires: 'Successful Hires',
    hero_successfulHiresCount: '10,000+',

    // === Filters ===
    filter_title: 'Filters',
    filter_clearAll: 'Clear All',
    filter_jobType: 'Job Type',
    filter_salaryRange: 'Salary Range',
    filter_district: 'District',
    filter_allDistricts: 'All Districts',
    filter_fullTime: 'Full-time',
    filter_partTime: 'Part-time / Freelance',
    filter_contract: 'Contractual',
    filter_below30k: 'Below 30,000 BDT',
    filter_30to60k: '30,000 - 60,000 BDT',
    filter_above60k: '60,000+ BDT',
    filter_btn: 'Filter',

    // === Sort ===
    sort_latest: 'Latest Posts',
    sort_salary: 'Highest Salary',
    sort_featured: 'Featured First',

    // === Job Listing ===
    jobs_found: 'jobs found',
    jobs_featured: '⭐ Featured Jobs',
    jobs_all: '📋 All Jobs',
    jobs_loading: 'Loading...',
    jobs_noResults: 'No jobs found',
    jobs_noResultsSub: 'Try different keywords or change filters',
    jobs_clearFilter: 'Clear Filters',

    // === Job Card ===
    card_urgent: '⚡ Urgent',
    card_featured: '⭐ Featured',
    card_deadline: 'Deadline:',
    card_viewDetails: 'View Details →',
    card_save: 'Save',
    card_unsave: 'Unsave',

    // === Job Detail ===
    detail_home: 'Home',
    detail_jobs: 'Jobs',
    detail_urgentHiring: '⚡ Urgent Hiring',
    detail_featured: '⭐ Featured',
    detail_positions: 'positions',
    detail_location: 'Location',
    detail_salary: 'Salary',
    detail_experience: 'Experience',
    detail_deadline: 'Deadline',
    detail_applyNow: 'Apply Now →',
    detail_saved: 'Saved',
    detail_save: 'Save',
    detail_description: 'Job Description',
    detail_skills: 'Required Skills',
    detail_requirements: 'Requirements',
    detail_benefits: 'Benefits',
    detail_companyProfile: 'View Company Profile',
    detail_applyToday: 'Apply Today!',
    detail_applyBeforeDeadline: 'Apply before the deadline',
    detail_deadlineLabel: 'Deadline:',
    detail_fillForm: 'Fill Application Form',
    detail_notFound: 'Job not found 😢',
    detail_goBack: '← Go Back',
    detail_review: 'reviews',

    // === Company Profile ===
    company_notFound: 'Company not found',
    company_goBack: '← Go Back',
    company_about: 'About the Company',
    company_benefits: 'Employee Benefits',
    company_activeJobs: 'Active Job Openings',
    company_openPositions: 'open positions',
    company_noJobs: 'No open positions at this time.',
    company_quickFacts: 'Quick Facts',
    company_industry: 'Industry',
    company_employees: 'Employees',
    company_founded: 'Founded',
    company_headquarters: 'Headquarters',
    company_website: 'Website',
    company_satisfaction: 'Employee Satisfaction',
    company_reviewCount: 'employee reviews',
    company_established: 'Est:',
    company_workEnvironment: 'Work Environment',
    company_careerGrowth: 'Career Growth',
    company_salaryBenefits: 'Salary & Benefits',
    company_workLifeBalance: 'Work-Life Balance',

    // === Apply Form ===
    apply_step1: 'Personal Info',
    apply_step2: 'Education & Experience',
    apply_step3: 'Documents',
    apply_step4: 'Confirmation',
    apply_notFound: 'Job not found',
    apply_goBack: '← Go Back',
    apply_fullName: 'Full Name *',
    apply_namePlaceholder: 'Enter your full name',
    apply_mobile: 'Mobile Number *',
    apply_email: 'Email Address *',
    apply_nid: 'National ID Number',
    apply_nidPlaceholder: 'NID Number (Optional)',
    apply_gender: 'Gender *',
    apply_selectGender: 'Select',
    apply_male: 'Male',
    apply_female: 'Female',
    apply_other: 'Other',
    apply_dob: 'Date of Birth',
    apply_district: 'District *',
    apply_selectDistrict: 'Select District',
    apply_address: 'Current Address',
    apply_addressPlaceholder: 'Enter your current address',
    apply_education: 'Highest Education *',
    apply_selectEducation: 'Select',
    apply_institution: 'Institution Name *',
    apply_institutionPlaceholder: 'University/College name',
    apply_passingYear: 'Passing Year *',
    apply_cgpa: 'CGPA / GPA',
    apply_educationSection: 'Education',
    apply_experienceSection: 'Work Experience (if any)',
    apply_prevCompany: 'Last Company Name',
    apply_prevDesignation: 'Designation',
    apply_totalExp: 'Total Experience (Years)',
    apply_prevSalary: 'Last Salary (BDT)',
    apply_coverLetter: 'Cover Letter *',
    apply_coverLetterTitle: 'Cover Letter & Portfolio',
    apply_portfolio: 'Portfolio / LinkedIn URL',
    apply_cvUpload: 'Upload CV / Resume',
    apply_cvFormat: 'PDF, DOC, DOCX — Max 5 MB',
    apply_chooseFile: 'Choose File',
    apply_confirmTitle: 'Confirm Application',
    apply_summary: 'Application Summary',
    apply_confirmName: 'Name',
    apply_confirmMobile: 'Mobile',
    apply_confirmEmail: 'Email',
    apply_confirmDistrict: 'District',
    apply_confirmEducation: 'Education',
    apply_confirmInstitution: 'Institution',
    apply_confirmPosition: 'Position',
    apply_confirmCompany: 'Company',
    apply_agreeText: 'I confirm that all the information above is correct and I agree to apply for this job.',
    apply_next: 'Next →',
    apply_prev: '← Previous',
    apply_submit: 'Submit Application ✓',
    apply_successTitle: 'Application Submitted Successfully!',
    apply_successSub1: 'at',
    apply_successSub2: 'Your application has been received.',
    apply_successEmail: 'A confirmation has been sent to your email',
    apply_successEmailSuffix: '.',
    apply_successContact: 'The company will contact you soon.',
    apply_moreJobs: 'Browse More Jobs',
    apply_savedJobs: 'Saved Jobs',
    apply_chars: 'characters',
    apply_freshGrad: 'Fresh Graduate (0 years)',
    apply_year1: '1 year',
    apply_year2: '2 years',
    apply_year3: '3 years',
    apply_year45: '4-5 years',
    apply_year5plus: '5+ years',

    // Validation
    val_nameRequired: 'Name is required',
    val_invalidPhone: 'Enter a valid mobile number (01XXXXXXXXX)',
    val_invalidEmail: 'Enter a valid email address',
    val_genderRequired: 'Please select gender',
    val_districtRequired: 'Please select district',
    val_educationRequired: 'Please select highest education',
    val_institutionRequired: 'Enter institution name',
    val_yearRequired: 'Enter passing year',
    val_coverLetterMin: 'Cover letter must be at least 50 characters',
    val_agreeRequired: 'You must agree to apply',

    // === Saved Jobs Page ===
    saved_title: 'Saved Jobs',
    saved_countSuffix: 'jobs saved',
    saved_countPrefix: 'You have',
    saved_empty: 'Save your favorite jobs',
    saved_clearAll: 'Clear All',
    saved_noSaved: 'No saved jobs',
    saved_noSavedSub: 'Click the bookmark icon on job cards to save your favorite jobs',
    saved_findJobs: 'Find Jobs →',
    saved_browserNote: 'Saved jobs are stored only in this browser.',
    saved_browseMore: 'Browse More Jobs →',

    // === Login / Register ===
    auth_loginTitle: 'Login to your account',
    auth_email: 'Email',
    auth_password: 'Password',
    auth_loginBtn: 'Login',
    auth_loginWait: 'Please wait...',
    auth_loginFailed: 'Login failed',
    auth_noAccount: "Don't have an account?",
    auth_register: 'Register',
    auth_registerTitle: 'Create a new account',
    auth_whoAreYou: 'Who are you?',
    auth_jobSeeker: '🔍 Job Seeker',
    auth_employer: '🏢 Employer',
    auth_fullName: 'Full Name *',
    auth_namePlaceholder: 'Your name',
    auth_emailPlaceholder: 'your@email.com',
    auth_companyName: 'Company Name *',
    auth_companyPlaceholder: 'Your company name',
    auth_mobile: 'Mobile Number',
    auth_passwordLabel: 'Password *',
    auth_passwordPlaceholder: 'At least 6 characters',
    auth_confirmPassword: 'Confirm Password *',
    auth_confirmPlaceholder: 'Re-enter password',
    auth_registerBtn: 'Register',
    auth_registerWait: 'Please wait...',
    auth_registerFailed: 'Registration failed',
    auth_hasAccount: 'Already have an account?',
    auth_loginLink: 'Login',
    auth_passwordMismatch: 'Passwords do not match',
    auth_companyRequired: 'Company name is required for vendors',

    // === Footer ===
    footer_tagline: "Bangladesh's best job portal.\nFind your dream job.",
    footer_jobSeekers: 'Job Seekers',
    footer_findJobs: 'Find Jobs',
    footer_savedJobs: 'Saved Jobs',
    footer_careerTips: 'Career Tips',
    footer_createCV: 'Create CV',
    footer_employers: 'Employers',
    footer_postJob: 'Post a Job',
    footer_cvDatabase: 'CV Database',
    footer_premiumPlan: 'Premium Plan',
    footer_contact: 'Contact',

    // === Language ===
    lang_bn: 'বাংলা',
    lang_en: 'English',
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('sholok_lang') || 'bn';
  });

  useEffect(() => {
    localStorage.setItem('sholok_lang', lang);
    document.documentElement.lang = lang === 'bn' ? 'bn' : 'en';
  }, [lang]);

  const t = (key) => translations[lang]?.[key] || translations.bn[key] || key;

  const toggleLang = () => setLang(prev => prev === 'bn' ? 'en' : 'bn');

  /** Resolve a localized string from a nested { en, bn } object or plain string */
  const translateField = (field, overrideLang = lang) => {
    if (!field) return '';
    if (typeof field === 'string') return field;
    return field[overrideLang] || field.bn || field.en || '';
  };

  const getLocalizedField = (obj, fieldName) => {
    if (!obj) return '';
    const raw = obj[fieldName];
    if (raw && typeof raw === 'object' && ('en' in raw || 'bn' in raw)) return translateField(raw);
    const suffix = lang === 'bn' ? 'Bn' : 'En';
    return obj[`${fieldName}${suffix}`] || obj[fieldName] || '';
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t, translateField, getLocalizedField }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used within LanguageProvider');
  return ctx;
}
